#imports

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3

#checking and cleaning october (2025)

In [29]:
url = "https://earthquake.phivolcs.dost.gov.ph/"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [30]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,12 October 2025 - 10:21 PM,13.52,120.33,001,2.0,018km N 50Â° W,Paluan (Occidental Mindoro)
1,12 October 2025 - 10:06 PM,11.15,124.04,030,1.8,013km N 30Â° E,City Of Bogo (Cebu)
2,12 October 2025 - 10:04 PM,07.41,126.86,022,1.8,042km N 59Â° E,Manay (Davao Oriental)
3,12 October 2025 - 09:58 PM,14.74,119.06,029,3.0,111km S 78Â° W,San Antonio (Zambales)
4,12 October 2025 - 09:56 PM,08.95,126.33,030,1.5,005km N 42Â° E,Cagwait (Surigao Del Sur)

In [31]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
152     12 October 2025 - 03:25 AM         07.13         127.00        018
153     12 October 2025 - 03:25 AM         07.13         127.00        018
176     12 October 2025 - 02:01 AM         08.98         126.50        026
178     12 October 2025 - 02:01 AM         08.98         126.50        026
186     12 October 2025 - 01:24 AM         07.14         126.98        023
187     12 October 2025 - 01:24 AM         07.14         126.98        023
232     11 October 2025 - 10:09 PM         07.24         126.85        023
233     11 October 2025 - 10:09 PM         07.24         126.85        023
281     11 October 2025 - 07:13 PM         07.18         126.95        033
282     11 October 2025 - 07:13 PM         07.18         126.95        033
305     11 October 2025 - 05:20 PM         07.00         127.04        006
306     11 October 2025 - 05:20 PM         07.00         127.04        006
342     11 October 2025 - 01:54 PM         07.35         126.89        032
343     11 October 2025 - 01:54 PM         07.35         126.89        032
431     11 October 2025 - 05:12 AM         09.00         122.71        009
436     11 October 2025 - 05:12 AM         09.00         122.71        009
485     11 October 2025 - 03:01 AM         07.12         126.44        033
487     11 October 2025 - 03:01 AM         07.12         126.44        033
678     10 October 2025 - 06:45 PM         07.36         127.03        024
679     10 October 2025 - 06:45 PM         07.36         127.03        024
1083    08 October 2025 - 05:03 AM         11.13         124.24        031
1084    08 October 2025 - 05:03 AM         11.13         124.24        031
1613    05 October 2025 - 11:15 AM         10.93         123.89        025
1614    05 October 2025 - 11:15 AM         10.93         123.89        025
2833    01 October 2025 - 05:46 AM         11.19         123.95        022
2834    01 October 2025 - 05:46 AM         11.19         123.95        022
2918    01 October 2025 - 01:52 AM         11.16         123.98        031
2919    01 October 2025 - 01:52 AM         11.16         123.98        031

      Mag     Coordinates                   Location
152   1.7  051km S 81Â° E     Manay (Davao Oriental)
153   1.7  051km S 81Â° E     Manay (Davao Oriental)
176   1.7  023km N 74Â° E  Cagwait (Surigao Del Sur)
178   1.7  023km N 74Â° E  Cagwait (Surigao Del Sur)
186   2.0  049km S 80Â° E     Manay (Davao Oriental)
187   2.0  049km S 80Â° E     Manay (Davao Oriental)
232   2.2  035km N 84Â° E     Manay (Davao Oriental)
233   2.2  035km N 84Â° E     Manay (Davao Oriental)
281   1.7  046km S 86Â° E     Manay (Davao Oriental)
282   1.7  046km S 86Â° E     Manay (Davao Oriental)
305   3.6  060km S 67Â° E     Manay (Davao Oriental)
306   3.6  060km S 67Â° E     Manay (Davao Oriental)
342   1.8  042km N 68Â° E     Manay (Davao Oriental)
343   1.8  042km N 68Â° E     Manay (Davao Oriental)
431   2.6  036km S 79Â° W   Siaton (Negros Oriental)
436   2.6  036km S 79Â° W   Siaton (Negros Oriental)
485   2.3  015km S 47Â° W     Manay (Davao Oriental)
487   2.3  015km S 47Â° W     Manay (Davao Oriental)
678   1.9  057km N 73Â° E     Manay (Davao Oriental)
679   1.9  057km N 73Â° E     Manay (Davao Oriental)
1083  1.7  030km N 71Â° E        City Of Bogo (Cebu)
1084  1.7  030km N 71Â° E        City Of Bogo (Cebu)
1613  2.2  016km S 39Â° W        City Of Bogo (Cebu)
1614  2.2  016km S 39Â° W        City Of Bogo (Cebu)
2833  1.8  016km N 10Â° W        City Of Bogo (Cebu)
2834  1.8  016km N 10Â° W        City Of Bogo (Cebu)
2918  2.6  013km N 01Â° W        City Of Bogo (Cebu)
2919  2.6  013km N 01Â° W        City Of Bogo (Cebu)


Dups No: 14


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df = df.drop_duplicates(keep="first")

In [32]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
152     12 October 2025 - 03:25 AM         07.13         127.00        018
153     12 October 2025 - 03:25 AM         07.13         127.00        018
176     12 October 2025 - 02:01 AM         08.98         126.50        026
178     12 October 2025 - 02:01 AM         08.98         126.50        026
186     12 October 2025 - 01:24 AM         07.14         126.98        023
187     12 October 2025 - 01:24 AM         07.14         126.98        023
232     11 October 2025 - 10:09 PM         07.24         126.85        023
233     11 October 2025 - 10:09 PM         07.24         126.85        023
281     11 October 2025 - 07:13 PM         07.18         126.95        033
282     11 October 2025 - 07:13 PM         07.18         126.95        033
305     11 October 2025 - 05:20 PM         07.00         127.04        006
306     11 October 2025 - 05:20 PM         07.00         127.04        006
342     11 October 2025 - 01:54 PM         07.35         126.89        032
343     11 October 2025 - 01:54 PM         07.35         126.89        032
431     11 October 2025 - 05:12 AM         09.00         122.71        009
436     11 October 2025 - 05:12 AM         09.00         122.71        009
485     11 October 2025 - 03:01 AM         07.12         126.44        033
487     11 October 2025 - 03:01 AM         07.12         126.44        033
678     10 October 2025 - 06:45 PM         07.36         127.03        024
679     10 October 2025 - 06:45 PM         07.36         127.03        024
1083    08 October 2025 - 05:03 AM         11.13         124.24        031
1084    08 October 2025 - 05:03 AM         11.13         124.24        031
1613    05 October 2025 - 11:15 AM         10.93         123.89        025
1614    05 October 2025 - 11:15 AM         10.93         123.89        025
2833    01 October 2025 - 05:46 AM         11.19         123.95        022
2834    01 October 2025 - 05:46 AM         11.19         123.95        022
2918    01 October 2025 - 01:52 AM         11.16         123.98        031
2919    01 October 2025 - 01:52 AM         11.16         123.98        031

      Mag     Coordinates                   Location
152   1.7  051km S 81Â° E     Manay (Davao Oriental)
153   1.7  051km S 81Â° E     Manay (Davao Oriental)
176   1.7  023km N 74Â° E  Cagwait (Surigao Del Sur)
178   1.7  023km N 74Â° E  Cagwait (Surigao Del Sur)
186   2.0  049km S 80Â° E     Manay (Davao Oriental)
187   2.0  049km S 80Â° E     Manay (Davao Oriental)
232   2.2  035km N 84Â° E     Manay (Davao Oriental)
233   2.2  035km N 84Â° E     Manay (Davao Oriental)
281   1.7  046km S 86Â° E     Manay (Davao Oriental)
282   1.7  046km S 86Â° E     Manay (Davao Oriental)
305   3.6  060km S 67Â° E     Manay (Davao Oriental)
306   3.6  060km S 67Â° E     Manay (Davao Oriental)
342   1.8  042km N 68Â° E     Manay (Davao Oriental)
343   1.8  042km N 68Â° E     Manay (Davao Oriental)
431   2.6  036km S 79Â° W   Siaton (Negros Oriental)
436   2.6  036km S 79Â° W   Siaton (Negros Oriental)
485   2.3  015km S 47Â° W     Manay (Davao Oriental)
487   2.3  015km S 47Â° W     Manay (Davao Oriental)
678   1.9  057km N 73Â° E     Manay (Davao Oriental)
679   1.9  057km N 73Â° E     Manay (Davao Oriental)
1083  1.7  030km N 71Â° E        City Of Bogo (Cebu)
1084  1.7  030km N 71Â° E        City Of Bogo (Cebu)
1613  2.2  016km S 39Â° W        City Of Bogo (Cebu)
1614  2.2  016km S 39Â° W        City Of Bogo (Cebu)
2833  1.8  016km N 10Â° W        City Of Bogo (Cebu)
2834  1.8  016km N 10Â° W        City Of Bogo (Cebu)
2918  2.6  013km N 01Â° W        City Of Bogo (Cebu)
2919  2.6  013km N 01Â° W        City Of Bogo (Cebu)


Dups No: 14


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [33]:
    df.to_csv("phivolcs_earthquakes_2025_10_October.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 2961 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,12 October 2025 - 10:21 PM,13.52,120.33,001,2.0,018km N 50Â° W,Paluan (Occidental Mindoro)
1,12 October 2025 - 10:06 PM,11.15,124.04,030,1.8,013km N 30Â° E,City Of Bogo (Cebu)
2,12 October 2025 - 10:04 PM,07.41,126.86,022,1.8,042km N 59Â° E,Manay (Davao Oriental)
3,12 October 2025 - 09:58 PM,14.74,119.06,029,3.0,111km S 78Â° W,San Antonio (Zambales)
4,12 October 2025 - 09:56 PM,08.95,126.33,030,1.5,005km N 42Â° E,Cagwait (Surigao Del Sur)

#checking and cleaning december (2019)

In [9]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2019/2019_November.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

ï»¿
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
	{font-family:"Arial","sans-serif";
	}
.auto-style12 {
	font-family: Arial;
}
 table.MsoNormalTable
	{font-size:10.0pt;
	font-family:"Times New Roman","serif"
}
p.MsoNormal
	{marg
Success!

In [10]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 December 2019 - 10:07 PM,11.44,124.83,113,2.0,002km N 39Â° W,Babatngon (Leyte)
1,31 December 2019 - 09:22 PM,06.74,125.14,007,2.2,009km S 57Â° W,Bansalan (Davao Del Sur)
2,31 December 2019 - 09:15 PM,07.57,124.84,032,2.1,009km S 71Â° W,Kadingilan (Bukidnon)
3,31 December 2019 - 08:11 PM,13.28,121.84,033,1.5,005km S 10Â° W,Gasan (Marinduque)
4,31 December 2019 - 08:09 PM,06.61,125.23,011,2.5,005km S 17Â° E,Kiblawan (Davao Del Sur)

In [11]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
639    19 December 2019 - 07:05 PM         09.90         122.23        003
640    19 December 2019 - 07:05 PM         09.90         122.23        003
658    19 December 2019 - 03:41 PM         06.74         124.99        033
663    19 December 2019 - 03:41 PM         06.74         124.99        033
979    16 December 2019 - 08:47 PM         06.55         125.22        024
1041   16 December 2019 - 12:04 PM         06.50         124.94        026
1042   16 December 2019 - 12:04 PM         06.50         124.94        026
1064   16 December 2019 - 08:47 PM         06.55         125.22        024
1376   10 December 2019 - 08:26 PM         10.25         126.02        019
1377   10 December 2019 - 08:26 PM         10.25         126.02        019
1378   10 December 2019 - 08:26 PM         10.25         126.02        019
1379   10 December 2019 - 08:26 PM         10.25         126.02        019
1380   10 December 2019 - 08:26 PM         10.25         126.02        019
1381   10 December 2019 - 08:26 PM         10.25         126.02        019

      Mag     Coordinates                          Location
639   3.2  025km N 52Â° W  Sipalay City (Negros Occidental)
640   3.2  025km N 52Â° W  Sipalay City (Negros Occidental)
658   2.2  009km S 32Â° E         Columbio (Sultan Kudarat)
663   2.2  009km S 32Â° E         Columbio (Sultan Kudarat)
979   3.4  011km S 06Â° E          Kiblawan (Davao Del Sur)
1041  2.2  005km S 09Â° W          Lutayan (Sultan Kudarat)
1042  2.2  005km S 09Â° W          Lutayan (Sultan Kudarat)
1064  3.4  011km S 06Â° E          Kiblawan (Davao Del Sur)
1376  2.6  026km N 14Â° W        Burgos (Surigao Del Norte)
1377  2.6  026km N 14Â° W        Burgos (Surigao Del Norte)
1378  2.6  026km N 14Â° W        Burgos (Surigao Del Norte)
1379  2.6  026km N 14Â° W        Burgos (Surigao Del Norte)
1380  2.6  026km N 14Â° W        Burgos (Surigao Del Norte)
1381  2.6  026km N 14Â° W        Burgos (Surigao Del Norte)


Dups No: 9


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [12]:
df = df.drop_duplicates(keep="first")

In [13]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [14]:
    df.to_csv("phivolcs_earthquakes_2019_12_December.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 1634 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 December 2019 - 10:07 PM,11.44,124.83,113,2.0,002km N 39Â° W,Babatngon (Leyte)
1,31 December 2019 - 09:22 PM,06.74,125.14,007,2.2,009km S 57Â° W,Bansalan (Davao Del Sur)
2,31 December 2019 - 09:15 PM,07.57,124.84,032,2.1,009km S 71Â° W,Kadingilan (Bukidnon)
3,31 December 2019 - 08:11 PM,13.28,121.84,033,1.5,005km S 10Â° W,Gasan (Marinduque)
4,31 December 2019 - 08:09 PM,06.61,125.23,011,2.5,005km S 17Â° E,Kiblawan (Davao Del Sur)

#checking and cleaning november (2019)

In [22]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2019/2019_October.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

ï»¿
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font-family:"Arial","sans-serif";
  }
.auto-style12 {
  font-
Success!

In [23]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 October 2019 - 11:45 PM,06.88,125.17,039,3.5,013km S 45Â° E,Makilala (Cotabato)
1,31 October 2019 - 11:44 PM,06.85,124.93,017,1.8,011km S 89Â° E,Tulunan (Cotabato)
2,31 October 2019 - 11:43 PM,07.09,125.24,008,1.7,014km S 85Â° E,Magpet (Cotabato)
3,31 October 2019 - 11:41 PM,06.84,124.80,024,2.5,004km S 64Â° W,Tulunan (Cotabato)
4,31 October 2019 - 11:38 PM,06.87,124.95,004,2.2,014km N 81Â° E,Tulunan (Cotabato)

In [24]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
417     29 October 2019 - 09:49 PM         06.78         124.81        020
422     29 October 2019 - 09:24 PM         06.96         125.08        007
423     29 October 2019 - 09:49 PM         06.78         124.81        020
424     29 October 2019 - 09:24 PM         06.96         125.08        007
466     29 October 2019 - 04:57 PM         06.66         124.89        038
468     29 October 2019 - 04:57 PM         06.66         124.89        038
742     24 October 2019 - 02:20 AM         06.70         124.80        058
743     24 October 2019 - 02:20 AM         06.70         124.80        058
1586    07 October 2019 - 08:49 PM         09.71         126.17        033
1590    07 October 2019 - 08:49 PM         09.71         126.17        033

      Mag     Coordinates                          Location
417   1.9  008km S 14Â° W                Tulunan (Cotabato)
422   3.6  030km N 67Â° E                Tulunan (Cotabato)
423   1.9  008km S 14Â° W                Tulunan (Cotabato)
424   3.6  030km N 67Â° E                Tulunan (Cotabato)
466   2.2  022km S 17Â° E                Tulunan (Cotabato)
468   2.2  022km S 17Â° E                Tulunan (Cotabato)
742   2.7  017km S 09Â° W                Tulunan (Cotabato)
743   2.7  017km S 09Â° W                Tulunan (Cotabato)
1586  2.1  008km S 11Â° E  General Luna (Surigao Del Norte)
1590  2.1  008km S 11Â° E  General Luna (Surigao Del Norte)


Dups No: 5


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [25]:
df = df.drop_duplicates(keep="first")

In [26]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [27]:
    df.to_csv("phivolcs_earthquakes_2019_10_October.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 1803 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 October 2019 - 11:45 PM,06.88,125.17,039,3.5,013km S 45Â° E,Makilala (Cotabato)
1,31 October 2019 - 11:44 PM,06.85,124.93,017,1.8,011km S 89Â° E,Tulunan (Cotabato)
2,31 October 2019 - 11:43 PM,07.09,125.24,008,1.7,014km S 85Â° E,Magpet (Cotabato)
3,31 October 2019 - 11:41 PM,06.84,124.80,024,2.5,004km S 64Â° W,Tulunan (Cotabato)
4,31 October 2019 - 11:38 PM,06.87,124.95,004,2.2,014km N 81Â° E,Tulunan (Cotabato)

#checking and cleaning october (2019)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2019/2019_November.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

ï»¿
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
	{font-family:"Arial","sans-serif";
	}
.auto-style12 {
	font-family: Arial;
}
 table.MsoNormalTable
	{font-size:10.0pt;
	font-family:"Times New Roman","serif"
}
p.MsoNormal
	{marg
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 November 2019 - 11:23 PM,08.51,124.16,012,2.7,015km N 86Â° W,Initao (Misamis Oriental)
1,30 November 2019 - 10:59 PM,09.75,122.02,008,3.1,008km S 88Â° W,Sipalay City (Negros Occidental)
2,30 November 2019 - 10:24 PM,16.26,120.01,042,1.8,008km S 64Â° E,Anda (Pangasinan)
3,30 November 2019 - 09:32 PM,05.52,126.48,047,3.2,104km S 67Â° E,Jose Abad Santos (Davao Occidental)
4,30 November 2019 - 09:19 PM,07.22,126.56,040,2.2,003km N 72Â° E,Manay (Davao Oriental)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
1516   02 November 2019 - 04:50 PM         06.89         125.05        019
1519   02 November 2019 - 04:50 PM         06.89         125.05        019
1637   01 November 2019 - 09:10 PM         06.82         125.04        016
1714   01 November 2019 - 09:10 PM         06.82         125.04        016

      Mag     Coordinates            Location
1516  2.5  025km N 79Â° E  Tulunan (Cotabato)
1519  2.5  025km N 79Â° E  Tulunan (Cotabato)
1637  2.6  023km S 80Â° E  Tulunan (Cotabato)
1714  2.6  023km S 80Â° E  Tulunan (Cotabato)


Dups No: 2


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df = df.drop_duplicates(keep="first")

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
    df.to_csv("phivolcs_earthquakes_2019_11_November.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 1785 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 November 2019 - 11:23 PM,08.51,124.16,012,2.7,015km N 86Â° W,Initao (Misamis Oriental)
1,30 November 2019 - 10:59 PM,09.75,122.02,008,3.1,008km S 88Â° W,Sipalay City (Negros Occidental)
2,30 November 2019 - 10:24 PM,16.26,120.01,042,1.8,008km S 64Â° E,Anda (Pangasinan)
3,30 November 2019 - 09:32 PM,05.52,126.48,047,3.2,104km S 67Â° E,Jose Abad Santos (Davao Occidental)
4,30 November 2019 - 09:19 PM,07.22,126.56,040,2.2,003km N 72Â° E,Manay (Davao Oriental)

#checking and cleaning (july 2021)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_July.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font-family:"Arial","sans-serif";
  }
.auto-style12 {
  font-fami
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 July 2021 - 08:58 PM,04.91,126.34,054,3.5,116km S 61Â° E,Sarangani (Davao Occidental)
1,31 July 2021 - 08:47 PM,06.01,126.17,154,3.3,057km S 68Â° E,Don Marcelino (Davao Occidental)
2,31 July 2021 - 08:00 PM,07.14,126.73,026,2.2,022km S 69Â° E,Manay (Davao Oriental)
3,31 July 2021 - 07:27 PM,07.62,127.38,031,2.6,091km N 87Â° E,Baganga (Davao Oriental)
4,31 July 2021 - 07:08 PM,09.89,126.44,054,2.2,033km N 69Â° E,General Luna (Surigao Del Norte)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
354,23 July 2021 - 08:19 PM,-,-,-,1.7,10km from Masbate City,None

In [ ]:
df = df.drop(index=354)

In [ ]:
    df.to_csv("phivolcs_earthquakes_2021_07_July.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 1099 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 July 2021 - 08:58 PM,04.91,126.34,054,3.5,116km S 61Â° E,Sarangani (Davao Occidental)
1,31 July 2021 - 08:47 PM,06.01,126.17,154,3.3,057km S 68Â° E,Don Marcelino (Davao Occidental)
2,31 July 2021 - 08:00 PM,07.14,126.73,026,2.2,022km S 69Â° E,Manay (Davao Oriental)
3,31 July 2021 - 07:27 PM,07.62,127.38,031,2.6,091km N 87Â° E,Baganga (Davao Oriental)
4,31 July 2021 - 07:08 PM,09.89,126.44,054,2.2,033km N 69Â° E,General Luna (Surigao Del Norte)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

#checking and cleaning (april 2021)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_April.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font-family:"Arial","sans-serif";
  }
.auto-style12 {
  font-fami
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 April 2021 - 10:12 PM,18.98,121.04,007,2.3,022km S 50Â° W,Dalupiri Island (Calayan) (Cagayan)
1,30 April 2021 - 08:02 PM,08.77,126.61,018,2.6,034km S 84Â° E,Marihatag (Surigao Del Sur)
2,30 April 2021 - 08:02 PM,07.00,125.08,024,1.9,004km N 07Â° W,Makilala (Cotabato)
3,30 April 2021 - 06:03 PM,06.33,125.81,143,3.1,020km N 39Â° E,Don Marcelino (Davao Occidental)
4,30 April 2021 - 05:59 PM,13.58,121.24,015,2.2,008km S 24Â° E,Lobo (Batangas)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
185      25 April 2021 - 01:45 AM         09.99         126.23        011
186      25 April 2021 - 01:45 AM         09.99         126.23        011

     Mag     Coordinates                          Location
185  2.6  024km N 21Â° E  General Luna (Surigao Del Norte)
186  2.6  024km N 21Â° E  General Luna (Surigao Del Norte)


Dups No: 1


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
698,04 April 2021 - 12:54 PM,-,-,1.932 km from Ibajay (Aklan),1.9,32 km from Ibajay (Aklan),None

In [ ]:
df = df.drop(index=698)

In [ ]:

    df.to_csv("phivolcs_earthquakes_2021_04_April.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 837 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 April 2021 - 10:12 PM,18.98,121.04,007,2.3,022km S 50Â° W,Dalupiri Island (Calayan) (Cagayan)
1,30 April 2021 - 08:02 PM,08.77,126.61,018,2.6,034km S 84Â° E,Marihatag (Surigao Del Sur)
2,30 April 2021 - 08:02 PM,07.00,125.08,024,1.9,004km N 07Â° W,Makilala (Cotabato)
3,30 April 2021 - 06:03 PM,06.33,125.81,143,3.1,020km N 39Â° E,Don Marcelino (Davao Occidental)
4,30 April 2021 - 05:59 PM,13.58,121.24,015,2.2,008km S 24Â° E,Lobo (Batangas)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

#checking and cleaning (December 2020)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2020/2020_December.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font-family:"Arial","sans-serif";
  }
.auto-style12 {
  font-fami
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 December 2020 - 11:18 PM,05.17,125.25,023,3.2,033km S 36Â° W,Sarangani (Davao Occidental)
1,31 December 2020 - 10:21 PM,17.37,120.61,010,2.7,012km S 53Â° W,Manabo (Abra)
2,31 December 2020 - 09:59 PM,06.00,124.88,023,2.2,020km N 41Â° W,Maasim (Sarangani)
3,31 December 2020 - 08:01 PM,10.22,126.09,009,2.0,022km N 04Â° E,Burgos (Surigao Del Norte)
4,31 December 2020 - 06:09 PM,04.48,126.41,006,3.1,151km S 47Â° E,Sarangani (Davao Occidental)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
441   20 December 2020 - 02:00 AM         09.65         126.22        032
442   20 December 2020 - 02:00 AM         09.65         126.22        032

     Mag     Coordinates                          Location
441  2.4  016km S 23Â° E  General Luna (Surigao Del Norte)
442  2.4  016km S 23Â° E  General Luna (Surigao Del Norte)


Dups No: 1


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
736,10 December 2020 - 09:20 PM,24.84,122.01,-,6.3,Taiwan Region,None

In [ ]:
df.at[736, "Coordinates"] = "24.782° N, 122.024° E"
df.at[736, "Depth (km)"] = "071"
df.at[736, "Location"] = "Taiwan Region"

In [ ]:
df.loc[730:740]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
730,11 December 2020 - 12:19 AM,11.90,124.11,008,3.3,007km N 75Â° E,Pio V. Corpuz (Masbate)
731,10 December 2020 - 11:37 PM,14.28,122.48,001,2.6,033km N 89Â° W,Paracale (Camarines Norte)
732,10 December 2020 - 11:30 PM,14.25,120.23,059,2.0,035km S 54Â° W,Mariveles (Bataan)
733,10 December 2020 - 10:46 PM,13.71,120.93,008,3.6,004km S 12Â° W,Mabini (Batangas)
734,10 December 2020 - 10:07 PM,02.38,125.89,074,3.9,339km S 09Â° E,Sarangani (Davao Occidental)
735,10 December 2020 - 09:21 PM,13.52,120.06,023,3.0,030km S 42Â° W,Looc (Occidental Mindoro)
736,10 December 2020 - 09:20 PM,24.84,122.01,071,6.3,"24.782° N, 122.024° E",Taiwan Region
737,10 December 2020 - 07:41 PM,13.93,120.24,024,2.7,015km N 58Â° E,Lubang (Occidental Mindoro)
738,10 December 2020 - 06:08 PM,06.24,126.41,056,1.6,059km S 40Â° E,Governor Generoso (Davao Oriental)
739,10 December 2020 - 05:48 PM,05.33,126.52,053,2.8,117km S 57Â° E,Jose Abad Santos (Davao Occidental)
740,10 December 2020 - 03:48 PM,14.36,122.73,029,2.5,009km N 26Â° E,Jose Panganiban (Camarines Norte)

In [ ]:
#df = df.drop(index=698)

In [ ]:

    df.to_csv("phivolcs_earthquakes_2020_12_December.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 998 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 December 2020 - 11:18 PM,05.17,125.25,023,3.2,033km S 36Â° W,Sarangani (Davao Occidental)
1,31 December 2020 - 10:21 PM,17.37,120.61,010,2.7,012km S 53Â° W,Manabo (Abra)
2,31 December 2020 - 09:59 PM,06.00,124.88,023,2.2,020km N 41Â° W,Maasim (Sarangani)
3,31 December 2020 - 08:01 PM,10.22,126.09,009,2.0,022km N 04Â° E,Burgos (Surigao Del Norte)
4,31 December 2020 - 06:09 PM,04.48,126.41,006,3.1,151km S 47Â° E,Sarangani (Davao Occidental)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

#checking and cleaning (August 2020)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2020/2020_August.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font-family:"Arial","sans-serif";
  }
.auto-style12 {
  font-fami
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 August 2020 - 11:56 PM,14.13,120.39,095,2.1,026km N 78Â° W,Nasugbu (Batangas)
1,31 August 2020 - 11:15 PM,06.95,126.57,103,4.2,029km S 07Â° E,Manay (Davao Oriental)
2,31 August 2020 - 10:57 PM,04.61,125.92,163,3.2,104km S 29Â° E,Sarangani (Davao Occidental)
3,31 August 2020 - 10:35 PM,06.03,126.26,119,3.0,072km S 17Â° E,Governor Generoso (Davao Oriental)
4,31 August 2020 - 10:33 PM,15.10,121.50,005,2.1,037km N 60Â° W,Panukulan (Quezon)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
390     22 August 2020 - 01:52 AM         12.23         123.89        025
391     22 August 2020 - 01:52 AM         12.23         123.89        025

     Mag     Coordinates             Location
390  2.1  027km N 26Â° W  Cataingan (Masbate)
391  2.1  027km N 26Â° W  Cataingan (Masbate)


Dups No: 1


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
1037,08 August 2020 - 08:30 AM,-,-,-,2.4,044km from Kidapawan City,None

In [ ]:
df.at[1037, "Coordinates"] = "044km"
df.at[1037, "Location"] = "Kidapawan City"

In [ ]:
df.loc[1035:1040]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
1035,08 August 2020 - 09:35 AM,09.86,122.12,014,2.9,033km N 70Â° W,Sipalay City (Negros Occidental)
1036,08 August 2020 - 09:11 AM,18.64,120.96,024,2.3,019km N 70Â° E,Pagudpud (Ilocos Norte)
1037,08 August 2020 - 08:30 AM,-,-,-,2.4,044km,Kidapawan City
1038,08 August 2020 - 08:27 AM,19.16,121.47,005,2.4,014km S 01Â° E,Calayan (Cagayan)
1039,08 August 2020 - 08:18 AM,15.25,122.32,032,2.0,058km N 41Â° E,Burdeos (Quezon)
1040,08 August 2020 - 08:15 AM,10.17,125.95,018,2.8,019km N 32Â° W,Santa Monica (Sapao) (Surigao Del Norte)

In [ ]:
#df = df.drop(index=698)

In [ ]:

    df.to_csv("phivolcs_earthquakes_2020_08_August.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 1294 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 August 2020 - 11:56 PM,14.13,120.39,095,2.1,026km N 78Â° W,Nasugbu (Batangas)
1,31 August 2020 - 11:15 PM,06.95,126.57,103,4.2,029km S 07Â° E,Manay (Davao Oriental)
2,31 August 2020 - 10:57 PM,04.61,125.92,163,3.2,104km S 29Â° E,Sarangani (Davao Occidental)
3,31 August 2020 - 10:35 PM,06.03,126.26,119,3.0,072km S 17Â° E,Governor Generoso (Davao Oriental)
4,31 August 2020 - 10:33 PM,15.10,121.50,005,2.1,037km N 60Â° W,Panukulan (Quezon)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

#checking and cleaning (June 2018)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2018/2018_June.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font-family:"Arial","sans-serif";
  }
.auto-style12 {
  font-family:
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    #df.to_csv("phivolcs_earthquakes(july test).csv", index=False, encoding="utf-8")
    #print(f"Data Saved: {len(df)} rows")
    display(df.head())

else:
    print("No Data")

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,ï»¿30 June 2018 - 11:46 PM,11.74,125.41,022,2.8,006km S 72Â° W,San Julian (Eastern Samar)
1,30 June 2018 - 10:02 PM,07.08,126.27,026,3.0,016km N 21Â° E,Mati (Davao Oriental)
2,30 June 2018 - 07:54 PM,15.69,121.88,005,2.7,035km S 78Â° E,Baler (Aurora)
3,30 June 2018 - 05:23 PM,10.07,122.08,031,3.0,049km N 46Â° W,Sipalay (Negros Occidental)
4,30 June 2018 - 05:19 PM,07.11,127.35,029,3.9,090km S 83Â° E,Manay (Davao Oriental)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    2
Longitude (ºE)                   2
Depth (km)                       2
Mag                              2
Coordinates                      3
Location                         5
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
178,21 June 2018 - 10:11 AM,09.00,126.68,029,2.2,043km N 78Â° E Cagwait(Surigao Del Sur),None
539,2018,None,None,None,None,None,None
540,Jan,Feb,Mar,Apr,May,None,None
541,2017,None,None,None,None,None,None
542,Jan,Feb,Mar,Apr,May,Jun,None

In [ ]:
df = df.drop(index=[539, 540, 541, 542])
df = df.reset_index(drop=True)

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
178,21 June 2018 - 10:11 AM,09.00,126.68,029,2.2,043km N 78Â° E Cagwait(Surigao Del Sur),None

In [ ]:
df.at[178, "Coordinates"] = "043km N 78Â° E"
df.at[178, "Location"] = "Cagwait(Surigao Del Sur)"

In [ ]:
df.loc[178:180]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
178,21 June 2018 - 10:11 AM,09.00,126.68,029,2.2,043km N 78Â° E,Cagwait(Surigao Del Sur)
179,21 June 2018 - 09:53 AM,11.65,124.44,016,2.6,010km S 69Â° E,Kawayan (Biliran)
180,21 June 2018 - 09:50 AM,15.66,119.94,028,1.8,004km N 09Â° E,Candelaria (Zambales)

In [ ]:
df.iloc[0] = df.iloc[0].str.replace("ï»¿", "", regex=False)

In [ ]:
df.head()

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 June 2018 - 11:46 PM,11.74,125.41,022,2.8,006km S 72Â° W,San Julian (Eastern Samar)
1,30 June 2018 - 10:02 PM,07.08,126.27,026,3.0,016km N 21Â° E,Mati (Davao Oriental)
2,30 June 2018 - 07:54 PM,15.69,121.88,005,2.7,035km S 78Â° E,Baler (Aurora)
3,30 June 2018 - 05:23 PM,10.07,122.08,031,3.0,049km N 46Â° W,Sipalay (Negros Occidental)
4,30 June 2018 - 05:19 PM,07.11,127.35,029,3.9,090km S 83Â° E,Manay (Davao Oriental)

In [ ]:
#df.loc[1035:1040]

In [ ]:
#df = df.drop(index=698)

In [ ]:

    df.to_csv("phivolcs_earthquakes_2018_06_June(2).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 539 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 June 2018 - 11:46 PM,11.74,125.41,022,2.8,006km S 72Â° W,San Julian (Eastern Samar)
1,30 June 2018 - 10:02 PM,07.08,126.27,026,3.0,016km N 21Â° E,Mati (Davao Oriental)
2,30 June 2018 - 07:54 PM,15.69,121.88,005,2.7,035km S 78Â° E,Baler (Aurora)
3,30 June 2018 - 05:23 PM,10.07,122.08,031,3.0,049km N 46Â° W,Sipalay (Negros Occidental)
4,30 June 2018 - 05:19 PM,07.11,127.35,029,3.9,090km S 83Â° E,Manay (Davao Oriental)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    2
Longitude (ºE)                   2
Depth (km)                       2
Mag                              2
Coordinates                      3
Location                         5
dtype: int64

#wtf is happening (2018) Jan - May

##January

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2018/2018_January.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

ï»¿
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="en-us" http-equiv="Content-Language"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Ea
  </title>
  <style type="text/css">
   span.auto-style12
	{font-family:"Arial","sans-serif";
	}
.auto-style12 {
	font-family: Arial;
}
 table.
Success!

In [ ]:
import re
import pandas as pd

all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]


page_text = soup.get_text(" ", strip=True)
CURRENT_YEAR = 2018
CURRENT_MONTH = "January"

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    rows = table.find_all("tr")

    header_index = None
    for i, tr in enumerate(rows):
        cells = [cell.get_text(strip=True) for cell in tr.find_all(["th","td","p","span"])]
        if cells and "Date" in cells[0]:
            header_index = i
            break

    if header_index is not None:
        for tr in rows[header_index+1:]:
            tds = tr.find_all("td")
            if not tds:
                continue

            cols = []
            for j, td in enumerate(tds):
                if j == 0:
                    # Prefer full text in <a>
                    link = td.find("a")
                    if link and re.search(r"\d{1,2}\s+\w+\s+\d{4}", link.get_text(strip=True)):
                        dt = link.get_text(strip=True)
                    else:

                        pieces = [s for s in td.stripped_strings]
                        joined = " ".join(pieces)


                        if re.fullmatch(r"\d{1,2}", joined) and len(pieces) > 1:
                            day = joined

                            m_time = re.search(r"(\d{1,2}:\d{2}\s*(AM|PM))", " ".join(pieces[1:]), flags=re.I)
                            if m_time:
                                dt = f"{day} {CURRENT_MONTH} {CURRENT_YEAR} - {m_time.group(1)}"
                            else:
                                dt = f"{day} {CURRENT_MONTH} {CURRENT_YEAR}"
                        else:
                            dt = joined
                    cols.append(dt)
                else:

                    cols.append(td.get_text(strip=True))

            if cols and len(cols) >= 6:
                all_rows.append(cols[:6])
        break

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)


    parts = df["Location"].str.split(r"\s*of\s*", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].fillna("").str.strip()

    df.loc[df["Location"] == "", "Location"] = df["Coordinates"]
    df.loc[df["Location"] == df["Coordinates"], "Coordinates"] = None


    df = df.replace("Â°", "°", regex=True)


    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]

    df.to_csv("phivolcs_earthquakes_2018_03_March.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 375 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,January,,,,,None,
1,31 January 2018 - 11:07 PM,13.20,125.48,025,2.8,082m N 29° E,Palapag (Northern Samar)
2,31 January 2018 - 10:32 PM,11.68,124.26,007,3.7,011 km S 87° W,Kawayan (Biliran)
3,31 January 2018 - 08:23 PM,13.05,120.56,034,3.5,018 km S 83° W,Santa Cruz (Occidental Mindoro)
4,31 January 2018 - 06:42 PM,14.11,120.43,122,1.9,021 km N 82° W,Nasugbu (Batangas)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      1
Location                         0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,January,,,,,None,

In [ ]:

df = df.drop(index=[0])
df = df.reset_index(drop=True)

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [ ]:
##df.at[178, "Coordinates"] = "043km N 78Â° E"
#df.at[178, "Location"] = "Cagwait(Surigao Del Sur)"

In [ ]:
#df.loc[178:180]

In [ ]:
#df.head()

In [ ]:
    df.to_csv("phivolcs_earthquakes_2018_01_January.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 374 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 January 2018 - 11:07 PM,13.20,125.48,025,2.8,082m N 29° E,Palapag (Northern Samar)
1,31 January 2018 - 10:32 PM,11.68,124.26,007,3.7,011 km S 87° W,Kawayan (Biliran)
2,31 January 2018 - 08:23 PM,13.05,120.56,034,3.5,018 km S 83° W,Santa Cruz (Occidental Mindoro)
3,31 January 2018 - 06:42 PM,14.11,120.43,122,1.9,021 km N 82° W,Nasugbu (Batangas)
4,31 January 2018 - 12:28 AM,18.71,120.87,022,3.3,017 km N 29° E,Pagudpud (Ilocos Norte)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Febuary

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2018/2018_February.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<html>
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Ea
  </title>
  <style>
   <!--
 table.MsoNormalTable
	{font-size:10.0pt;
	font-family:"Times New Roman","serif"
}
p
	{margin-right:0in;
	margin-left:0in;
	font-size:12.0pt;
	font-family:"Times New Roman","serif";
	}
p.MsoNormal
	{margin-bottom:.0001pt;
	font-size:10.0pt;
	font-family:"Times New Roman","serif";
	margin-left:0in; margin-right:0in; margin-
Success!

In [ ]:
import re
import pandas as pd

all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

page_text = soup.get_text(" ", strip=True)
CURRENT_YEAR = 2018
CURRENT_MONTH = "February"

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    rows = table.find_all("tr")

    header_index = None
    for i, tr in enumerate(rows):
        cells = [cell.get_text(strip=True) for cell in tr.find_all(["th","td","p","span"])]
        if cells and "Date" in cells[0]:
            header_index = i
            break

    if header_index is not None:
        for tr in rows[header_index+1:]:
            tds = tr.find_all("td")
            if not tds:
                continue

            cols = []
            for j, td in enumerate(tds):
                if j == 0:
                    # Prefer full text in <a>
                    link = td.find("a")
                    if link and re.search(r"\d{1,2}\s+\w+\s+\d{4}", link.get_text(strip=True)):
                        dt = link.get_text(strip=True)
                    else:

                        pieces = [s for s in td.stripped_strings]
                        joined = " ".join(pieces)


                        if re.fullmatch(r"\d{1,2}", joined) and len(pieces) > 1:
                            day = joined

                            m_time = re.search(r"(\d{1,2}:\d{2}\s*(AM|PM))", " ".join(pieces[1:]), flags=re.I)
                            if m_time:
                                dt = f"{day} {CURRENT_MONTH} {CURRENT_YEAR} - {m_time.group(1)}"
                            else:
                                dt = f"{day} {CURRENT_MONTH} {CURRENT_YEAR}"
                        else:
                            dt = joined
                    cols.append(dt)
                else:

                    cols.append(td.get_text(strip=True))

            if cols and len(cols) >= 6:
                all_rows.append(cols[:6])
        break

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)

    parts = df["Location"].str.split(r"\s*of\s*", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].fillna("").str.strip()

    df.loc[df["Location"] == "", "Location"] = df["Coordinates"]
    df.loc[df["Location"] == df["Coordinates"], "Coordinates"] = None


    df = df.replace("Â°", "°", regex=True)


    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]

    df.to_csv("phivolcs_earthquakes_2018_03_March.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 367 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,FEBRUARY,,,,,None,
1,28 February 2018 - 11:57 PM,14.10,122.52,001,2.0,016 km N 06° W,Tagkawayan (Quezon)
2,28 February 2018 - 11:43 PM,08.99,122.78,011,2.0,029 km S 74° W,Siaton (Negros Oriental)
3,28 February 2018 - 11:05 PM,13.25,120.20,014,2.5,034 km S 58° W,Paluan (Occidental Mindoro)
4,28 February 2018 - 10:22 PM,14.27,120.50,139,2.0,019 km S 06° E,Mariveles (Bataan)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      2
Location                         0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,FEBRUARY,,,,,None,
35,26 February 2018 - 09:54 AM,05.33,125.37,182,2.8,None,017 km S45° WoF Sarangani (Davao Occidental)

In [ ]:
df.at[35, "Coordinates"] = "017 km S45° W"
df.at[35, "Location"] = "Sarangani (Davao Occidental)"

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,FEBRUARY,,,,,None,

In [ ]:

df = df.drop(index=[0])
df = df.reset_index(drop=True)

In [ ]:
##df.at[178, "Coordinates"] = "043km N 78Â° E"
#df.at[178, "Location"] = "Cagwait(Surigao Del Sur)"

In [ ]:
df.loc[33:40]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
33,26 February 2018 - 12:37 PM,13.91,120.53,170,2.2,014 km N51° W,Calatagan \r\n\t\t\t(Batangas)
34,26 February 2018 - 09:54 AM,05.33,125.37,182,2.8,017 km S45° W,Sarangani (Davao Occidental)
35,26 February 2018 - 06:36 AM,10.20,123.71,032,3.0,005 km S82° W,Naga (Cebu)
36,26 February 2018 - 06:20 A,20.27,122.02,003,3.6,014 km S39° E,Uyugan (Batanes)
37,26 February 2018 - 03:20 AM,08.73,126.61,026,3.2,035 km S78° E,Marihatag (Surigao Del Sur)
38,26 February 2018 - 01:47 AM,17.80,120.89,032,2.2,006 km N48° W,Tineg (Abra)
39,26 February 2018 - 12:16 AM,19.71,120.44,051,3.0,117 km N67° W,Calayan (Cagayan)
40,25 February 2018 - 09:31 PM,13.75,123.86,028,2.4,009 km S84° W,Caramoan (Camarines Sur)

In [ ]:
#df.head()

In [ ]:

    df.to_csv("phivolcs_earthquakes_2018_02_Febuary.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 366 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,28 February 2018 - 11:57 PM,14.10,122.52,001,2.0,016 km N 06° W,Tagkawayan (Quezon)
1,28 February 2018 - 11:43 PM,08.99,122.78,011,2.0,029 km S 74° W,Siaton (Negros Oriental)
2,28 February 2018 - 11:05 PM,13.25,120.20,014,2.5,034 km S 58° W,Paluan (Occidental Mindoro)
3,28 February 2018 - 10:22 PM,14.27,120.50,139,2.0,019 km S 06° E,Mariveles (Bataan)
4,28 February 2018 - 09:11 PM,05.65,126.99,132,3.3,151 km S 42° E,Governor Generoso (Davao Oriental)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##March

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2018/2018_March.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

ï»¿
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Ea
  </title>
  <style type="text/css">
   table.MsoNormalTable
	{font-size:10.0pt;
	font-family:"Times New Roman","serif"
}
p.MsoNormal
	{margin-bottom:.0001pt;
	font-size:10.0pt;
	font-family:"Times
Success!

In [ ]:
import re
import pandas as pd

all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

page_text = soup.get_text(" ", strip=True)
CURRENT_YEAR = 2018
CURRENT_MONTH = "March"

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    rows = table.find_all("tr")

    header_index = None
    for i, tr in enumerate(rows):
        cells = [cell.get_text(strip=True) for cell in tr.find_all(["th","td","p","span"])]
        if cells and "Date" in cells[0]:
            header_index = i
            break

    if header_index is not None:
        for tr in rows[header_index+1:]:
            tds = tr.find_all("td")
            if not tds:
                continue

            cols = []
            for j, td in enumerate(tds):
                if j == 0:
                    # Prefer full text in <a>
                    link = td.find("a")
                    if link and re.search(r"\d{1,2}\s+\w+\s+\d{4}", link.get_text(strip=True)):
                        dt = link.get_text(strip=True)
                    else:

                        pieces = [s for s in td.stripped_strings]
                        joined = " ".join(pieces)


                        if re.fullmatch(r"\d{1,2}", joined) and len(pieces) > 1:
                            day = joined

                            m_time = re.search(r"(\d{1,2}:\d{2}\s*(AM|PM))", " ".join(pieces[1:]), flags=re.I)
                            if m_time:
                                dt = f"{day} {CURRENT_MONTH} {CURRENT_YEAR} - {m_time.group(1)}"
                            else:
                                dt = f"{day} {CURRENT_MONTH} {CURRENT_YEAR}"
                        else:
                            dt = joined
                    cols.append(dt)
                else:

                    cols.append(td.get_text(strip=True))

            if cols and len(cols) >= 6:
                all_rows.append(cols[:6])
        break

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)

    parts = df["Location"].str.split(r"\s*of\s*", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].fillna("").str.strip()

    df.loc[df["Location"] == "", "Location"] = df["Coordinates"]
    df.loc[df["Location"] == df["Coordinates"], "Coordinates"] = None


    df = df.replace("Â°", "°", regex=True)


    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]

    df.to_csv("phivolcs_earthquakes_2018_03_March.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 370 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,MARCH,,,,,None,
1,31 March 2018 - 09:49 PM,06.33,126.83,015,2.8,090 km S 28° E,Tarragona (Davao Oriental)
2,31 March 2018 - 08:31 PM,11.33,125.64,011,2.0,002 km N 55° E,Hernani (Eastern Samar)
3,31 March 2018 - 07:48 PM,05.11,127.51,072,3.7,227 km S 68° E,Jose Abad Santos (Davao Occidental)
4,31 March 2018 - 07:23 PM,07.26,123.51,009,3.3,024 km S 26° E,Tabina (Zamboanga del Sur)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      2
Location                         0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,MARCH,,,,,None,
43,29 March 2018 - 10:56 AM,13.57,120.86,086,2.3,None,020 km N 45° E Abra De Ilog (Occidental Mindoro)

In [ ]:

df.at[43, "Coordinates"] = "020 km N 45° E"
df.at[43, "Location"] = "Abra De Ilog (Occidental Mindoro"

In [ ]:

df = df.drop(index=[0])
df = df.reset_index(drop=True)

In [ ]:
df.loc[40:45]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
40,29 March 2018 - 02:21 PM,15.48,119.77,023,2.9,015 km N 71° W,Palauig (Zambales)
41,29 March 2018 - 11:10 AM,10.20,123.10,014,2.0,021 km N 64° W,Guihulngan (Negros Oriental)
42,29 March 2018 - 10:56 AM,13.57,120.86,086,2.3,020 km N 45° E,Abra De Ilog (Occidental Mindoro
43,29 March 2018 - 10:30 AM,14.90,119.10,034,3.2,105 km S 56° W,Palauig (Zambales)
44,29 March 2018 - 09:32 AM,21.16,121.28,023,2.3,071 km N 56° W,Itbayat (Batanes)
45,29 March 2018 - 09:05 AM,15.12,122.02,017,2.2,033 km N 13° E,Burdeos (Quezon)

In [ ]:
df.head()

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 March 2018 - 09:49 PM,06.33,126.83,015,2.8,090 km S 28° E,Tarragona (Davao Oriental)
1,31 March 2018 - 08:31 PM,11.33,125.64,011,2.0,002 km N 55° E,Hernani (Eastern Samar)
2,31 March 2018 - 07:48 PM,05.11,127.51,072,3.7,227 km S 68° E,Jose Abad Santos (Davao Occidental)
3,31 March 2018 - 07:23 PM,07.26,123.51,009,3.3,024 km S 26° E,Tabina (Zamboanga del Sur)
4,31 March 2018 - 06:26 PM,09.15,125.44,023,3.1,012 km N 74° W,Cabadbaran (Agusan del Norte)

In [ ]:

    df.to_csv("phivolcs_earthquakes_2018_03_March.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 369 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 March 2018 - 09:49 PM,06.33,126.83,015,2.8,090 km S 28° E,Tarragona (Davao Oriental)
1,31 March 2018 - 08:31 PM,11.33,125.64,011,2.0,002 km N 55° E,Hernani (Eastern Samar)
2,31 March 2018 - 07:48 PM,05.11,127.51,072,3.7,227 km S 68° E,Jose Abad Santos (Davao Occidental)
3,31 March 2018 - 07:23 PM,07.26,123.51,009,3.3,024 km S 26° E,Tabina (Zamboanga del Sur)
4,31 March 2018 - 06:26 PM,09.15,125.44,023,3.1,012 km N 74° W,Cabadbaran (Agusan del Norte)

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##April

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2018/2018_April.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

ï»¿
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Ea
  </title>
  <style type="text/css">
   table.MsoNormalTable
	{font-size:10.0pt;
	font-family:"Times New Roman","serif"
}
p.MsoNormal
	{margin-bottom:.0001pt;
	font-size:10.0pt;
	font-family:"Times
Success!

In [ ]:
import re
import pandas as pd


CURRENT_YEAR = 2018
CURRENT_MONTH = "April"

MONTHS = ["January","February","March","April","May","June",
          "July","August","September","October","November","December"]

def extract_datetime_from_td(td):


    pieces = [s for s in td.stripped_strings]
    joined = " ".join(pieces).replace("–", "-")


    if joined in MONTHS:
        return None

    if re.fullmatch(r"\d{1,2}", joined):
        return None
    m = re.search(
        r"\b(?P<day>\d{1,2})\b.*?\b(?P<month>January|February|March|April|May|June|"
        r"July|August|September|October|November|December)\b"
        r"\s+(?P<year>\d{4})\s*-\s*(?P<time>\d{1,2}:\d{2})\s*(?P<ampm>AM|PM)?",
        joined, flags=re.I
    )
    if m:
        day   = m.group("day")
        month = m.group("month").title()
        year  = m.group("year")
        time  = m.group("time")
        ampm  = (m.group("ampm") or "").upper()
        return f"{day} {month} {year} - {time}{(' ' + ampm) if ampm else ''}".strip()

    m_day  = re.search(r"\b(\d{1,2})\b", joined)
    m_time = re.search(r"(\d{1,2}:\d{2})", joined)
    m_ampm = re.search(r"\b(AM|PM)\b", joined, flags=re.I)
    if m_day and m_time:
        ampm = m_ampm.group(1).upper() if m_ampm else ""
        return f"{m_day.group(1)} {CURRENT_MONTH} {CURRENT_YEAR} - {m_time.group(1)}{(' ' + ampm) if ampm else ''}".strip()


    return joined


# ---------------- SCRAPE + CLEAN ---------------- #
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    rows = table.find_all("tr")


    for i, tr in enumerate(rows):
        cells = [c.get_text(strip=True) for c in tr.find_all(["th","td","p","span"])]
        if cells and "Date" in cells[0]:
            header_index = i
            break

    if header_index is None:
        continue

    for tr in rows[header_index+1:]:
        tds = tr.find_all("td")
        if not tds:
            continue


        dt = extract_datetime_from_td(tds[0])
        if dt is None:  #month/day separators
            continue


        rest = [td.get_text(strip=True) for td in tds[1:6]]
        row = [dt] + rest
        if len(row) >= 6:
            all_rows.append(row[:6])
    break


if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)


    parts = df["Location"].str.split(r"\s*of\s*", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].fillna("").str.strip()
    df.loc[df["Location"] == "", "Location"] = df["Coordinates"]
    df.loc[df["Location"] == df["Coordinates"], "Coordinates"] = None

    df = df.replace("Â°", "°", regex=True)


    df = df[["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)",
             "Depth (km)","Mag","Coordinates","Location"]]


    df.to_csv("phivolcs_earthquakes_2018_04_April.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 467 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,APRIL,,,,,None,
1,30 April 2018 - 10:46 PM,07.49,126.41,013,3.1,092 km N 88° E,Baculin (Davao Oriental)
2,30 April 2018 - 09:57 PM,08.15,126.00,012,2.8,003 km S 40° E,Bunawan (Agusan Del Sur)
3,30 April 2018 - 08:37 PM,06.86,125.09,016,2.7,011 km S 02° W,Makilala (North Cotabato)
4,30 April 2018 - 06:11 PM,10.16,122.21,004,2.6,043 km S 46° E,Anini-y (Antique)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      1
Location                         0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,APRIL,,,,,None,

In [ ]:
'''
df.at[43, "Coordinates"] = "020 km N 45° E"
df.at[43, "Location"] = "Abra De Ilog (Occidental Mindoro"
'''

'\ndf.at[43, "Coordinates"] = "020 km N 45° E"\ndf.at[43, "Location"] = "Abra De Ilog (Occidental Mindoro"\n'

In [ ]:

df = df.drop(index=[0])
df = df.reset_index(drop=True)

In [ ]:
#df.loc[40:45]

In [ ]:
df.head()

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 April 2018 - 10:46 PM,07.49,126.41,013,3.1,092 km N 88° E,Baculin (Davao Oriental)
1,30 April 2018 - 09:57 PM,08.15,126.00,012,2.8,003 km S 40° E,Bunawan (Agusan Del Sur)
2,30 April 2018 - 08:37 PM,06.86,125.09,016,2.7,011 km S 02° W,Makilala (North Cotabato)
3,30 April 2018 - 06:11 PM,10.16,122.21,004,2.6,043 km S 46° E,Anini-y (Antique)
4,30 April 2018 - 12:20 PM,12.76,122.80,031,1.9,045 km S 25° W,San Pascual (Masbate)

In [ ]:

    df.to_csv("phivolcs_earthquakes_2018_04_April.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 466 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 April 2018 - 10:46 PM,07.49,126.41,013,3.1,092 km N 88° E,Baculin (Davao Oriental)
1,30 April 2018 - 09:57 PM,08.15,126.00,012,2.8,003 km S 40° E,Bunawan (Agusan Del Sur)
2,30 April 2018 - 08:37 PM,06.86,125.09,016,2.7,011 km S 02° W,Makilala (North Cotabato)
3,30 April 2018 - 06:11 PM,10.16,122.21,004,2.6,043 km S 46° E,Anini-y (Antique)
4,30 April 2018 - 12:20 PM,12.76,122.80,031,1.9,045 km S 25° W,San Pascual (Masbate)

In [ ]:
#df.isnull().sum()

##May

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2018/2018_May.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

ï»¿
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Ea
  </title>
  <style type="text/css">
   span.auto-style12
	{font-family:"Arial","sans-serif";
	}
.auto-style12 {
	font-family: Arial;
}
 table.MsoNormalTable
	{font-size:10.0pt;
	font-family:"Times
Success!

In [ ]:
import re
import pandas as pd

CURRENT_YEAR = 2018
CURRENT_MONTH = "May"

MONTHS = ["January","February","March","April","May","June",
          "July","August","September","October","November","December"]

def extract_datetime_from_td(td):
    pieces = [s for s in td.stripped_strings if s.strip()]
    joined = " ".join(pieces).replace("–", "-")

    # Ignore month headers like "May" or day-only rows
    if joined in MONTHS or re.fullmatch(r"\d{1,2}", joined):
        return None

    # Case 1: full datetime in one string (normal)
    m = re.search(
        r"\b(?P<day>\d{1,2})\b.*?\b(?P<month>January|February|March|April|May|June|"
        r"July|August|September|October|November|December)\b"
        r"\s+(?P<year>\d{4})\s*-\s*(?P<time>\d{1,2}:\d{2})\s*(?P<ampm>AM|PM)?",
        joined, flags=re.I
    )
    if m:
        day   = m.group("day")
        month = m.group("month").title()
        year  = m.group("year")
        time  = m.group("time")
        ampm  = (m.group("ampm") or "").upper()
        return f"{day} {month} {year} - {time}{(' ' + ampm) if ampm else ''}".strip()

    # Case 2: split across multiple spans → ["2", "May 2018 - 01:10 AM"]
    if len(pieces) >= 2 and re.fullmatch(r"\d{1,2}", pieces[0]) and any(m in pieces[1] for m in MONTHS):
        return f"{pieces[0]} {pieces[1]}"

    # Case 3: fallback (day + time only, use CURRENT_MONTH/YEAR)
    m_day  = re.search(r"\b(\d{1,2})\b", joined)
    m_time = re.search(r"(\d{1,2}:\d{2})", joined)
    m_ampm = re.search(r"\b(AM|PM)\b", joined, flags=re.I)
    if m_day and m_time:
        ampm = m_ampm.group(1).upper() if m_ampm else ""
        return f"{m_day.group(1)} {CURRENT_MONTH} {CURRENT_YEAR} - {m_time.group(1)}{(' ' + ampm) if ampm else ''}".strip()

    return joined


# ---------------- SCRAPE + CLEAN ---------------- #
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    rows = table.find_all("tr")

    header_index = None
    for i, tr in enumerate(rows):
        cells = [c.get_text(strip=True) for c in tr.find_all(["th","td","p","span"])]
        if cells and "Date" in cells[0]:
            header_index = i
            break

    if header_index is None:
        continue

    for tr in rows[header_index+1:]:
        tds = tr.find_all("td")
        if not tds:
            continue

        dt = extract_datetime_from_td(tds[0])
        if dt is None:  # skip month/day separators
            continue

        rest = [td.get_text(strip=True) for td in tds[1:6]]
        row = [dt] + rest
        if len(row) >= 6:
            all_rows.append(row[:6])
    break

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)

    parts = df["Location"].str.split(r"\s*of\s*", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].fillna("").str.strip()
    df.loc[df["Location"] == "", "Location"] = df["Coordinates"]
    df.loc[df["Location"] == df["Coordinates"], "Coordinates"] = None

    df = df.replace("Â°", "°", regex=True)

    df = df[["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)",
             "Depth (km)","Mag","Coordinates","Location"]]

    df.to_csv("phivolcs_earthquakes_2018_05_May.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 599 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,MAY,,,,,None,
1,31 May 2018 - 11:44 PM,04.02,126.50,039,4.7,194 km S 36° E,Sarangani (Davao Occidental)
2,31 May 2018 - 11:27 PM,17.38,121.83,024,2.5,006 km S 67° E,Santo Tomas (Isabela)
3,31 May 2018 - 11:22 PM,06.18,126.35,001,2.7,060 km S 31° E,Governor Generoso (Davao Oriental)
4,31 May 2018 - 11:19 PM,15.07,120.01,018,2.0,007 km N 84° W,San Felipe (Zambales)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      1
Location                         0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,MAY,,,,,None,

In [ ]:
'''
df.at[43, "Coordinates"] = "020 km N 45° E"
df.at[43, "Location"] = "Abra De Ilog (Occidental Mindoro"
'''

'\ndf.at[43, "Coordinates"] = "020 km N 45° E"\ndf.at[43, "Location"] = "Abra De Ilog (Occidental Mindoro"\n'

In [ ]:

df = df.drop(index=[0])
df = df.reset_index(drop=True)

In [ ]:
#df.loc[40:45]

In [ ]:
df.head()

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 May 2018 - 11:44 PM,04.02,126.50,039,4.7,194 km S 36° E,Sarangani (Davao Occidental)
1,31 May 2018 - 11:27 PM,17.38,121.83,024,2.5,006 km S 67° E,Santo Tomas (Isabela)
2,31 May 2018 - 11:22 PM,06.18,126.35,001,2.7,060 km S 31° E,Governor Generoso (Davao Oriental)
3,31 May 2018 - 11:19 PM,15.07,120.01,018,2.0,007 km N 84° W,San Felipe (Zambales)
4,31 May 2018 - 09:56 PM,12.90,124.33,031,2.1,021 km N 79° E,Barcelona (Sorsogon)

In [ ]:

    df.to_csv("phivolcs_earthquakes_2018_05_May.csv", index=False, encoding="utf-8-sig")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 598 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 May 2018 - 11:44 PM,04.02,126.50,039,4.7,194 km S 36° E,Sarangani (Davao Occidental)
1,31 May 2018 - 11:27 PM,17.38,121.83,024,2.5,006 km S 67° E,Santo Tomas (Isabela)
2,31 May 2018 - 11:22 PM,06.18,126.35,001,2.7,060 km S 31° E,Governor Generoso (Davao Oriental)
3,31 May 2018 - 11:19 PM,15.07,120.01,018,2.0,007 km N 84° W,San Felipe (Zambales)
4,31 May 2018 - 09:56 PM,12.90,124.33,031,2.1,021 km N 79° E,Barcelona (Sorsogon)

In [ ]:
#df.isnull().sum()

##july

In [ ]:
#fetching on that specific link (For october)
#iba naman sa september and onwards ha

url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2018/2018_July.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font-family:"Arial","sans-serif";
  }
.auto-style12 {
  font-family:
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()
#-------ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
        "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]
#-------ocd lang to
    df.to_csv("phivolcs_earthquakes_2018_07_July.csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 508 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,ï»¿31 July 2018 - 11:05 PM,18.05,121.71,007,2.4,008km S 81Â° E,Gattaran (Cagayan)
1,31 July 2018 - 07:13 PM,16.50,120.91,009,2.3,017km S 21Â° E,Kabayan (Benguet)
2,31 July 2018 - 06:29 PM,12.53,123.59,006,2.2,016km S 36Â° E,Monreal (Masbate)
3,31 July 2018 - 05:47 PM,12.45,123.52,007,2.9,004km S 47Â° E,Baleno (Masbate)
4,31 July 2018 - 02:51 PM,10.39,125.17,004,3.8,009km N 64Â° W,Hinundayan (Southern Leyte)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

#2021

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

months = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

year = 2021
all_data = []

for month in months:
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{year}/{year}_{month}.html"
    print(f"Fetching {url}...choo-choo....choo-choo")

    response = requests.get(url, verify=False)
    if response.status_code != 200:
        print(f"Failed: {month}")
        continue

    soup = BeautifulSoup(response.text, "html.parser")
    tables = soup.find_all("table", {"class": "MsoNormalTable"})

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                cols = [td.get_text(strip=True) for td in tr.find_all("td")]
                if cols:
                    all_data.append(cols)


headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

df = pd.DataFrame([row[:6] for row in all_data], columns=headers)


df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()

#Reorder
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
        "Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]


df.to_csv(f"phivolcs_earthquakes_{year}.csv", index=False, encoding="utf-8")
print(f"Saved {len(df)} rows for {year}")

Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_January.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_February.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_March.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_April.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_May.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_June.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_July.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_August.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_September.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_October.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_November.html ...
Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2021/2021_December.html ...
Saved 12056 rows for 2021

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3
import re

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

MONTHS = ["January","February","March","April","May","June",
          "July","August","September","October","November","December"]

YEAR = 2021
MONTH_ORDER = MONTHS

BASE = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{y}/{y}_{m}.html"
COLS = ["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)","Depth (km)","Mag","Location"]

def scrape_one_month(year:int, month_name:str) -> pd.DataFrame:
    url = BASE.format(y=year, m=month_name)
    r = requests.get(url, verify=False)
    if r.status_code != 200:
        print(f"{month_name} {year}: page not found ({r.status_code})")
        return pd.DataFrame(columns=COLS)

    soup = BeautifulSoup(r.text, "html.parser")
    all_rows = []

    for table in soup.find_all("table", {"class": "MsoNormalTable"}):
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                tds = [td.get_text(strip=True) for td in tr.find_all("td")]
                if tds:
                    all_rows.append(tds)

    if not all_rows:
        return pd.DataFrame(columns=COLS)

    df = pd.DataFrame([row[:6] for row in all_rows], columns=COLS)

    parts = df["Location"].str.split(r"\bof\b", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].str.strip()

    for c in ["Coordinates","Location"]:
        df[c] = df[c].str.replace("Â°", "°", regex=False)


    df = df[["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)",
             "Depth (km)","Mag","Coordinates","Location"]]

    return df


monthly_frames = []
for m in MONTH_ORDER:
    df_m = scrape_one_month(YEAR, m)
    if df_m.empty:
        print(f"{m} {YEAR}: no rows")
        continue

    #dup check
    cnt = df_m.duplicated().sum()
    duplicates = df_m[df_m.duplicated(keep=False)]
    print(f"\n===== {m} {YEAR} =====")
    if cnt > 0:
        print("Duplicates found:\n", duplicates)
    print("\nDups No:", cnt)
    print("This is earthquake data so duplicates are okay. Double check with website if unsure.")

    #null check
    print("\nNulls per column:\n", df_m.isnull().sum())

    month_idx = MONTHS.index(m) + 1
    out_name = f"phivolcs_earthquakes_{YEAR}_{month_idx:02d}_{m}.csv"
    df_m.to_csv(out_name, index=False, encoding="utf-8")
    print(f"✅ Saved {len(df_m)} rows → {out_name}")

    monthly_frames.append(df_m)

===== January 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 781 rows → phivolcs_earthquakes_2021_01_January.csv

===== February 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 824 rows → phivolcs_earthquakes_2021_02_February.csv

===== March 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 818 rows → phivolcs_earthquakes_2021_03_March.csv

===== April 2021 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
185      25 April 2021 - 01:45 AM         09.99         126.23        011
186      25 April 2021 - 01:45 AM         09.99         126.23        011

     Mag    Coordinates                          Location
185  2.6  024km N 21° E  General Luna (Surigao Del Norte)
186  2.6  024km N 21° E  General Luna (Surigao Del Norte)

Dups No: 1
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64
✅ Saved 838 rows → phivolcs_earthquakes_2021_04_April.csv

===== May 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 931 rows → phivolcs_earthquakes_2021_05_May.csv

===== June 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 1574 rows → phivolcs_earthquakes_2021_06_June.csv

===== July 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64
✅ Saved 1100 rows → phivolcs_earthquakes_2021_07_July.csv

===== August 2021 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
468     18 August 2021 - 03:53 AM         06.09         127.48        020
469     18 August 2021 - 03:53 AM         06.09         127.48        020

     Mag    Coordinates                    Location
468  3.5  158km S 47° E  Tarragona (Davao Oriental)
469  3.5  158km S 47° E  Tarragona (Davao Oriental)

Dups No: 1
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 1339 rows → phivolcs_earthquakes_2021_08_August.csv

===== September 2021 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
337  21 September 2021 - 07:37 AM         05.57         126.83        020
340  21 September 2021 - 07:37 AM         05.57         126.83        020

     Mag    Coordinates                             Location
337  2.8  137km S 74° E  Jose Abad Santos (Davao Occidental)
340  2.8  137km S 74° E  Jose Abad Santos (Davao Occidental)

Dups No: 1
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 1000 rows → phivolcs_earthquakes_2021_09_September.csv

===== October 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 1147 rows → phivolcs_earthquakes_2021_10_October.csv

===== November 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 959 rows → phivolcs_earthquakes_2021_11_November.csv

===== December 2021 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
✅ Saved 745 rows → phivolcs_earthquakes_2021_12_December.csv

#2020

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3
import re

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

MONTHS = ["January","February","March","April","May","June",
          "July","August","September","October","November","December"]

YEAR = 2020
MONTH_ORDER = MONTHS

BASE = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{y}/{y}_{m}.html"
COLS = ["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)","Depth (km)","Mag","Location"]

def scrape_one_month(year:int, month_name:str) -> pd.DataFrame:
    url = BASE.format(y=year, m=month_name)
    r = requests.get(url, verify=False)
    if r.status_code != 200:
        print(f"{month_name} {year}: page not found ({r.status_code})")
        return pd.DataFrame(columns=COLS)

    soup = BeautifulSoup(r.text, "html.parser")
    all_rows = []

    for table in soup.find_all("table", {"class": "MsoNormalTable"}):
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                tds = [td.get_text(strip=True) for td in tr.find_all("td")]
                if tds:
                    all_rows.append(tds)

    if not all_rows:
        return pd.DataFrame(columns=COLS)

    df = pd.DataFrame([row[:6] for row in all_rows], columns=COLS)

    parts = df["Location"].str.split(r"\bof\b", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].str.strip()

    for c in ["Coordinates","Location"]:
        df[c] = df[c].str.replace("Â°", "°", regex=False)


    df = df[["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)",
             "Depth (km)","Mag","Coordinates","Location"]]

    return df


monthly_frames = []
for m in MONTH_ORDER:
    df_m = scrape_one_month(YEAR, m)
    if df_m.empty:
        print(f"{m} {YEAR}: no rows")
        continue

    #dup check
    cnt = df_m.duplicated().sum()
    duplicates = df_m[df_m.duplicated(keep=False)]
    print(f"\n===== {m} {YEAR} =====")
    if cnt > 0:
        print("Duplicates found:\n", duplicates)
    print("\nDups No:", cnt)
    print("This is earthquake data so duplicates are okay. Double check with website if unsure.")

    #null check
    print("\nNulls per column:\n", df_m.isnull().sum())

    month_idx = MONTHS.index(m) + 1
    out_name = f"phivolcs_earthquakes_{YEAR}_{month_idx:02d}_{m}.csv"
    df_m.to_csv(out_name, index=False, encoding="utf-8")
    print(f"Saved {len(df_m)} rows → {out_name}")

    monthly_frames.append(df_m)

===== January 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1712 rows → phivolcs_earthquakes_2020_01_January.csv

===== February 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 862 rows → phivolcs_earthquakes_2020_02_February.csv

===== March 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1113 rows → phivolcs_earthquakes_2020_03_March.csv

===== April 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1345 rows → phivolcs_earthquakes_2020_04_April.csv

===== May 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1307 rows → phivolcs_earthquakes_2020_05_May.csv

===== June 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1249 rows → phivolcs_earthquakes_2020_06_June.csv

===== July 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1088 rows → phivolcs_earthquakes_2020_07_July.csv

===== August 2020 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
390     22 August 2020 - 01:52 AM         12.23         123.89        025
391     22 August 2020 - 01:52 AM         12.23         123.89        025

     Mag    Coordinates             Location
390  2.1  027km N 26° W  Cataingan (Masbate)
391  2.1  027km N 26° W  Cataingan (Masbate)

Dups No: 1
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64
Saved 1294 rows → phivolcs_earthquakes_2020_08_August.csv

===== September 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1062 rows → phivolcs_earthquakes_2020_09_September.csv

===== October 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1137 rows → phivolcs_earthquakes_2020_10_October.csv

===== November 2020 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 880 rows → phivolcs_earthquakes_2020_11_November.csv

===== December 2020 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
441   20 December 2020 - 02:00 AM         09.65         126.22        032
442   20 December 2020 - 02:00 AM         09.65         126.22        032

     Mag    Coordinates                          Location
441  2.4  016km S 23° E  General Luna (Surigao Del Norte)
442  2.4  016km S 23° E  General Luna (Surigao Del Norte)

Dups No: 1
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64
Saved 998 rows → phivolcs_earthquakes_2020_12_December.csv

#2019

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3
import re

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

MONTHS = ["January","February","March","April","May","June",
          "July","August","September","October","November","December"]

YEAR = 2019
BASE = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{y}/{y}_{m}.html"
COLS = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"]

def scrape_one_month(year:int, month_name:str) -> pd.DataFrame:
    url = BASE.format(y=year, m=month_name)
    r = requests.get(url, verify=False)
    if r.status_code != 200:
        print(f"{month_name} {year}: page not found ({r.status_code})")
        return pd.DataFrame(columns=COLS)

    soup = BeautifulSoup(r.text, "html.parser")
    tables = soup.find_all("table", class_="MsoNormalTable")
    all_rows = []

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if not ths and len(table.find_all("tr")) < 5:
            continue
        for tr in table.find_all("tr")[1:]:
            tds = [td.get_text(" ", strip=True) for td in tr.find_all("td")]
            if len(tds) >= 6:
                all_rows.append(tds[:6])

    if not all_rows:
        print(f"{month_name} {year}: still no data rows found.")
        return pd.DataFrame(columns=COLS)

    df = pd.DataFrame(all_rows, columns=COLS)

    parts = df["Location"].str.split(r"\b(?:of|from|near)\b", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"] = parts[1].fillna("").str.strip()

    for c in ["Coordinates", "Location"]:
        df[c] = df[c].replace(r"\s+", " ", regex=True).replace("Â°", "°", regex=False)

    df = df[["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
             "Depth (km)", "Mag", "Coordinates", "Location"]]
    return df

monthly_frames = []
for m in MONTHS:
    print(f"\n===== {m} {YEAR} =====")
    df_m = scrape_one_month(YEAR, m)
    if df_m.empty:
        print(f"{m} {YEAR}: no rows")
        continue
    cnt = df_m.duplicated().sum()
    if cnt > 0:
        print("Duplicates found:\n", df_m[df_m.duplicated(keep=False)].head())
    print("\nDups No:", cnt)
    print("This is earthquake data so duplicates are okay. Double check with website if unsure.")
    print("\nNulls per column:\n", df_m.isna().sum())
    month_idx = MONTHS.index(m) + 1
    out_name = f"phivolcs_earthquakes_{YEAR}_{month_idx:02d}_{m}.csv"
    df_m.to_csv(out_name, index=False, encoding="utf-8-sig")
    print(f"Saved {len(df_m)} rows {out_name}")
    monthly_frames.append(df_m)

===== January 2019 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 621 rows phivolcs_earthquakes_2019_01_January.csv

===== February 2019 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 930 rows phivolcs_earthquakes_2019_02_February.csv

===== March 2019 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 883 rows phivolcs_earthquakes_2019_03_March.csv

===== April 2019 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
172      28 April 2019 - 05:08 AM         09.48         126.35        014
173      28 April 2019 - 05:08 AM         09.48         126.35        014
679      21 April 2019 - 03:44 AM         06.18         125.92        014
680      21 April 2019 - 03:44 AM         06.18         125.92        014

     Mag      Coordinates                          Location
172  2.1  029 km N 36Â° E          Cortes (Surigao Del Sur)
173  2.1  029 km N 36Â° E          Cortes (Surigao Del Sur)
679  2.5  025 km S 82Â° E  Don Marcelino (Davao Occidental)
680  2.5  025 km S 82Â° E  Don Marcelino (Davao Occidental)

Dups No: 2
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1254 rows phivolcs_earthquakes_2019_04_April.csv

===== May 2019 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
240        21 May 2019 - 02:22 AM         12.20         124.17        008
241        21 May 2019 - 02:22 AM         12.20         124.17        008
686        08 May 2019 - 03:17 AM         09.61         126.62        011
687        08 May 2019 - 03:17 AM         09.61         126.62        011

     Mag      Coordinates                          Location
240  1.7  012 km S 41Â° E      San Vicente (Northern Samar)
241  1.7  012 km S 41Â° E      San Vicente (Northern Samar)
686  2.6  054 km S 69Â° E  General Luna (Surigao Del Norte)
687  2.6  054 km S 69Â° E  General Luna (Surigao Del Norte)

Dups No: 2
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 976 rows phivolcs_earthquakes_2019_05_May.csv

===== June 2019 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
441       13 June 2019 - 01:37 AM         10.61         124.62        003
442       13 June 2019 - 01:37 AM         10.61         124.62        003
784                           Jan           Feb            Mar        Apr
785                           Jan           Feb            Mar        Apr
786                           Jan           Feb            Mar        Apr

     Mag      Coordinates          Location
441  2.4  017 km N 48Â° W  Inopacan (Leyte)
442  2.4  017 km N 48Â° W  Inopacan (Leyte)
784  May              Jun
785  May              Jun
786  May              Jun

Dups No: 3
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 787 rows phivolcs_earthquakes_2019_06_June.csv

===== July 2019 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 863 rows phivolcs_earthquakes_2019_07_July.csv

===== August 2019 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 553 rows phivolcs_earthquakes_2019_08_August.csv

===== September 2019 =====
Duplicates found:
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  Mag  \
30  30 September 2019 - 06:16 AM         05.66         126.64        054  3.1
31  30 September 2019 - 06:16 AM         05.66         126.64        054  3.1
39  30 September 2019 - 02:15 AM         06.00         125.55        033  2.9
40  30 September 2019 - 02:15 AM         06.00         125.55        033  2.9

        Coordinates                             Location
30  116 km S 78Â° E  Jose Abad Santos (Davao Occidental)
31  116 km S 78Â° E  Jose Abad Santos (Davao Occidental)
39  027 km S 36Â° W     Don Marcelino (Davao Occidental)
40  027 km S 36Â° W     Don Marcelino (Davao Occidental)

Dups No: 2
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 897 rows phivolcs_earthquakes_2019_09_September.csv

===== October 2019 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
417    29 October 2019 - 09:49 PM         06.78         124.81        020
422    29 October 2019 - 09:24 PM         06.96         125.08        007
423    29 October 2019 - 09:49 PM         06.78         124.81        020
424    29 October 2019 - 09:24 PM         06.96         125.08        007
466    29 October 2019 - 04:57 PM         06.66         124.89        038

     Mag      Coordinates            Location
417  1.9  008 km S 14Â° W  Tulunan (Cotabato)
422  3.6  030 km N 67Â° E  Tulunan (Cotabato)
423  1.9  008 km S 14Â° W  Tulunan (Cotabato)
424  3.6  030 km N 67Â° E  Tulunan (Cotabato)
466  2.2  022 km S 17Â° E  Tulunan (Cotabato)

Dups No: 5
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1808 rows phivolcs_earthquakes_2019_10_October.csv

===== November 2019 =====
Duplicates found:
      Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
1516   02 November 2019 - 04:50 PM         06.89         125.05        019
1519   02 November 2019 - 04:50 PM         06.89         125.05        019
1637   01 November 2019 - 09:10 PM         06.82         125.04        016
1714   01 November 2019 - 09:10 PM         06.82         125.04        016

      Mag      Coordinates            Location
1516  2.5  025 km N 79Â° E  Tulunan (Cotabato)
1519  2.5  025 km N 79Â° E  Tulunan (Cotabato)
1637  2.6  023 km S 80Â° E  Tulunan (Cotabato)
1714  2.6  023 km S 80Â° E  Tulunan (Cotabato)

Dups No: 2
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1787 rows phivolcs_earthquakes_2019_11_November.csv

===== December 2019 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
639   19 December 2019 - 07:05 PM         09.90         122.23        003
640   19 December 2019 - 07:05 PM         09.90         122.23        003
658   19 December 2019 - 03:41 PM         06.74         124.99        033
663   19 December 2019 - 03:41 PM         06.74         124.99        033
979   16 December 2019 - 08:47 PM         06.55         125.22        024

     Mag      Coordinates                          Location
639  3.2  025 km N 52Â° W  Sipalay City (Negros Occidental)
640  3.2  025 km N 52Â° W  Sipalay City (Negros Occidental)
658  2.2  009 km S 32Â° E         Columbio (Sultan Kudarat)
663  2.2  009 km S 32Â° E         Columbio (Sultan Kudarat)
979  3.4  011 km S 06Â° E          Kiblawan (Davao Del Sur)

Dups No: 9
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1643 rows phivolcs_earthquakes_2019_12_December.csv

#2018

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3
import re

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

MONTHS = ["January","February","March","April","May","June",
          "July","August","September","October","November","December"]

YEAR = 2018
MONTH_ORDER = MONTHS

BASE = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{y}/{y}_{m}.html"
COLS = ["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)","Depth (km)","Mag","Location"]

def scrape_one_month(year:int, month_name:str) -> pd.DataFrame:
    url = BASE.format(y=year, m=month_name)
    r = requests.get(url, verify=False)
    if r.status_code != 200:
        print(f"{month_name} {year}: page not found ({r.status_code})")
        return pd.DataFrame(columns=COLS)

    soup = BeautifulSoup(r.text, "html.parser")
    all_rows = []

    for table in soup.find_all("table", {"class": "MsoNormalTable"}):
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                tds = [td.get_text(strip=True) for td in tr.find_all("td")]
                if tds:
                    all_rows.append(tds)

    if not all_rows:
        return pd.DataFrame(columns=COLS)

    df = pd.DataFrame([row[:6] for row in all_rows], columns=COLS)

    parts = df["Location"].str.split(r"\bof\b", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].str.strip()

    for c in ["Coordinates","Location"]:
        df[c] = df[c].str.replace("Â°", "°", regex=False)


    df = df[["Date - Time (Philippine Time)","Latitude (ºN)","Longitude (ºE)",
             "Depth (km)","Mag","Coordinates","Location"]]

    return df


monthly_frames = []
for m in MONTH_ORDER:
    df_m = scrape_one_month(YEAR, m)
    if df_m.empty:
        print(f"{m} {YEAR}: no rows")
        continue

    #dup check
    cnt = df_m.duplicated().sum()
    duplicates = df_m[df_m.duplicated(keep=False)]
    print(f"\n===== {m} {YEAR} =====")
    if cnt > 0:
        print("Duplicates found:\n", duplicates)
    print("\nDups No:", cnt)
    print("This is earthquake data so duplicates are okay. Double check with website if unsure.")

    #null check
    print("\nNulls per column:\n", df_m.isnull().sum())

    month_idx = MONTHS.index(m) + 1
    out_name = f"phivolcs_earthquakes_{YEAR}_{month_idx:02d}_{m}.csv"
    df_m.to_csv(out_name, index=False, encoding="utf-8")
    print(f"Saved {len(df_m)} rows → {out_name}")

    monthly_frames.append(df_m)

January 2018: no rows
February 2018: no rows
March 2018: no rows
April 2018: no rows
May 2018: no rows

===== June 2018 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    2
Longitude (ºE)                   2
Depth (km)                       2
Mag                              2
Coordinates                      3
Location                         5
dtype: int64
Saved 543 rows → phivolcs_earthquakes_2018_06_June.csv

===== July 2018 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 508 rows → phivolcs_earthquakes_2018_07_July.csv

===== August 2018 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 529 rows → phivolcs_earthquakes_2018_08_August.csv

===== September 2018 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         1
dtype: int64
Saved 581 rows → phivolcs_earthquakes_2018_09_September.csv

===== October 2018 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         4
dtype: int64
Saved 708 rows → phivolcs_earthquakes_2018_10_October.csv

===== November 2018 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 659 rows → phivolcs_earthquakes_2018_11_November.csv

===== December 2018 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 561 rows → phivolcs_earthquakes_2018_12_December.csv

#2017

In [ ]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

MONTHS_FULL = ["January","February","March","April","May","June",
               "July","August","September","October","November","December"]

HEADERS = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

def scrape_one_month(year: int, month_full: str) -> pd.DataFrame:
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{year}/{year}_{month_full}.html"
    print(f"\n📂 Fetching {url} …")

    try:
        r = requests.get(url, verify=False, timeout=30)
    except Exception as e:
        print(f"  ⚠️ error: {e}")
        return pd.DataFrame(columns=HEADERS + ["Coordinates"])

    if r.status_code != 200:
        print(f"  ⚠️ {month_full} {year}: page not found ({r.status_code})")
        return pd.DataFrame(columns=HEADERS + ["Coordinates"])

    soup = BeautifulSoup(r.text, "html.parser")
    tables = soup.find_all("table", {"class": "MsoNormalTable"})
    if not tables:
        print("  ⚠️ no tables found")
        return pd.DataFrame(columns=HEADERS + ["Coordinates"])

    all_rows = []
    for table in tables:
        rows = table.find_all("tr")

        # Identify header row by keyword
        header_index = None
        for i, tr in enumerate(rows):
            txt = " ".join([c.get_text(" ", strip=True).lower() for c in tr.find_all(["th","td","p","span"])])
            if "date" in txt and "location" in txt:
                header_index = i
                break

        if header_index is None:
            continue

        for tr in rows[header_index+1:]:
            tds = tr.find_all("td")
            if not tds or len(tds) < 6:
                continue

            # ✅ Date-time (prefer <a> if present)
            date_td = tds[0]
            link = date_td.find("a")
            if link:
                dt = link.get_text(strip=True)
            else:
                dt = date_td.get_text(" ", strip=True)

            if not dt or dt.upper() in MONTHS_FULL or re.fullmatch(r"\d{1,2}", dt):
                continue

            # ✅ The rest of the row
            rest = [td.get_text(" ", strip=True) for td in tds[1:6]]

            row = [dt] + rest
            if len(row) == 6:
                all_rows.append(row)

        if all_rows:
            break

    if not all_rows:
        print("  ⚠️ no rows")
        return pd.DataFrame(columns=HEADERS + ["Coordinates"])

    df = pd.DataFrame(all_rows, columns=HEADERS)

    # Split "Coordinates" and "Location"
    parts = df["Location"].str.split(r"\s*of\s*", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"]    = parts[1].fillna("").str.strip()
    df.loc[df["Location"] == "", "Location"] = df["Coordinates"]
    df.loc[df["Location"] == df["Coordinates"], "Coordinates"] = None

    df = df.replace("Â°", "°", regex=True)

    # Reorder
    df = df[["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
             "Depth (km)", "Mag", "Coordinates", "Location"]]

    # Save CSV
    month_idx = MONTHS_FULL.index(month_full) + 1
    out_name = f"phivolcs_earthquakes_{year}_{month_idx:02d}_{month_full}.csv"
    df.to_csv(out_name, index=False, encoding="utf-8-sig")

    # Duplicates
    duplicates = df[df.duplicated()]
    cnt = len(duplicates)
    if cnt > 0:
        print("Duplicates found:\n", duplicates)
    print("\nDups No:", cnt)
    print("This is earthquake data so duplicates are okay. Double check with website if unsure.")

    # Nulls
    print("\nNulls per column:\n", df.isnull().sum())

    print(f"  ✅ saved {len(df)} rows → {out_name}")
    return df


def scrape_year(year: int):
    for m in MONTHS_FULL:
        scrape_one_month(year, m)


# -------- RUN --------
scrape_year(2017)

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_January.html …
  ⚠️ no rows

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_February.html …
  ⚠️ no rows

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_March.html …
  ⚠️ no rows

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_April.html …
  ⚠️ no rows

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_May.html …
  ⚠️ no rows

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_June.html …

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      3
Location                         0
dtype: int64
  ✅ saved 363 rows → phivolcs_earthquakes_2017_06_June.csv

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_July.html …

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      1
Location                         0
dtype: int64
  ✅ saved 9 rows → phivolcs_earthquakes_2017_07_July.csv

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_August.html …

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      7
Location                         0
dtype: int64
  ✅ saved 406 rows → phivolcs_earthquakes_2017_08_August.csv

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_September.html …

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)     0
Latitude (ºN)                     0
Longitude (ºE)                    0
Depth (km)                        0
Mag                               0
Coordinates                      28
Location                          0
dtype: int64
  ✅ saved 357 rows → phivolcs_earthquakes_2017_09_September.csv

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_October.html …

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      2
Location                         0
dtype: int64
  ✅ saved 264 rows → phivolcs_earthquakes_2017_10_October.csv

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_November.html …

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      5
Location                         0
dtype: int64
  ✅ saved 383 rows → phivolcs_earthquakes_2017_11_November.csv

📂 Fetching https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2017/2017_December.html …

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      1
Location                         0
dtype: int64
  ✅ saved 308 rows → phivolcs_earthquakes_2017_12_December.csv

#2025

In [28]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3
import re

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

MONTHS = ["January","February","March","April","May","June",
          "July","August","September","October","November","December"]

YEAR = 2025
BASE = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{y}/{y}_{m}.html"
COLS = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"]

def scrape_one_month(year:int, month_name:str) -> pd.DataFrame:
    url = BASE.format(y=year, m=month_name)
    r = requests.get(url, verify=False)
    if r.status_code != 200:
        print(f"{month_name} {year}: page not found ({r.status_code})")
        return pd.DataFrame(columns=COLS)

    soup = BeautifulSoup(r.text, "html.parser")
    tables = soup.find_all("table", class_="MsoNormalTable")
    all_rows = []

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if not ths and len(table.find_all("tr")) < 5:
            continue
        for tr in table.find_all("tr")[1:]:
            tds = [td.get_text(" ", strip=True) for td in tr.find_all("td")]
            if len(tds) >= 6:
                all_rows.append(tds[:6])

    if not all_rows:
        print(f"{month_name} {year}: still no data rows found.")
        return pd.DataFrame(columns=COLS)

    df = pd.DataFrame(all_rows, columns=COLS)

    parts = df["Location"].str.split(r"\b(?:of|from|near)\b", n=1, regex=True, expand=True)
    df["Coordinates"] = parts[0].str.strip()
    df["Location"] = parts[1].fillna("").str.strip()

    for c in ["Coordinates", "Location"]:
        df[c] = df[c].replace(r"\s+", " ", regex=True).replace("Â°", "°", regex=False)

    df = df[["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
             "Depth (km)", "Mag", "Coordinates", "Location"]]
    return df

monthly_frames = []
for m in MONTHS:
    print(f"\n===== {m} {YEAR} =====")
    df_m = scrape_one_month(YEAR, m)
    if df_m.empty:
        print(f"{m} {YEAR}: no rows")
        continue
    cnt = df_m.duplicated().sum()
    if cnt > 0:
        print("Duplicates found:\n", df_m[df_m.duplicated(keep=False)].head())
    print("\nDups No:", cnt)
    print("This is earthquake data so duplicates are okay. Double check with website if unsure.")
    print("\nNulls per column:\n", df_m.isna().sum())
    month_idx = MONTHS.index(m) + 1
    out_name = f"phivolcs_earthquakes_{YEAR}_{month_idx:02d}_{m}.csv"
    df_m.to_csv(out_name, index=False, encoding="utf-8-sig")
    print(f"Saved {len(df_m)} rows {out_name}")
    monthly_frames.append(df_m)

===== January 2025 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1441 rows phivolcs_earthquakes_2025_01_January.csv

===== February 2025 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
514   16 February 2025 - 07:47 AM         10.41         123.22        005
601   16 February 2025 - 07:47 AM         10.41         123.22        005

     Mag      Coordinates                           Location
514  2.5  002 km N 10Â° E  City Of Canlaon (Negros Oriental)
601  2.5  002 km N 10Â° E  City Of Canlaon (Negros Oriental)

Dups No: 1
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1213 rows phivolcs_earthquakes_2025_02_February.csv

===== March 2025 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1401 rows phivolcs_earthquakes_2025_03_March.csv

===== April 2025 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1332 rows phivolcs_earthquakes_2025_04_April.csv

===== May 2025 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1559 rows phivolcs_earthquakes_2025_05_May.csv

===== June 2025 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1637 rows phivolcs_earthquakes_2025_06_June.csv

===== July 2025 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1421 rows phivolcs_earthquakes_2025_07_July.csv

===== August 2025 =====

Dups No: 0
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1632 rows phivolcs_earthquakes_2025_08_August.csv

===== September 2025 =====
Duplicates found:
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
853  13 September 2025 - 06:57 AM         09.24         126.90        015
854  13 September 2025 - 06:57 AM         09.24         126.90        015

     Mag      Coordinates                   Location
853  2.3  074 km N 66Â° E  Bayabas (Surigao Del Sur)
854  2.3  074 km N 66Â° E  Bayabas (Surigao Del Sur)

Dups No: 1
This is earthquake data so duplicates are okay. Double check with website if unsure.

Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Saved 1509 rows phivolcs_earthquakes_2025_09_September.csv

===== October 2025 =====
October 2025: page not found (404)
October 2025: no rows

===== November 2025 =====
November 2025: page not found (404)
November 2025: no rows

===== December 2025 =====
December 2025: page not found (404)
December 2025: no rows