#Imports

In [1]:
import re
import pandas as pd

#Jan 2017

In [23]:
import re
import pandas as pd

x  = "/content/phivolcs_2017_January.txt"
y = "phivolcs_earthquakes_2017_01_January.csv"

#patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

records = []
state = 0#for header
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        if state == 0:
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue
        if state == 1:# latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue
        if state == 2:# longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0#reset here after format break
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:#magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:#location
            cur["Location"] = line
            records.append(cur)
            state = 0
            cur = {}


df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])


for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
#--separation
df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]
#---

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())

#----save---#
df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {OUTPUT_FILE}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Data Saved: 341 rows → phivolcs_earthquakes(2017_January).csv

In [18]:
df.head(10)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 Jan 2017 - 11:55 PM,5.13,126.10,14,3.5,073 km S 67° E,Sarangani (Davao Occidental)
1,31 Jan 2017 - 11:42 PM,9.82,125.50,37,2.5,003 km N 16° E,Surigao City (Surigao Del Norte)
2,31 Jan 2017 - 05:17 PM,9.23,122.57,19,3.7,022 km S 21° W,Basay (Negros Oriental)
3,31 Jan 2017 - 05:26 AM,8.78,123.27,14,2.0,022 km N 20° W,Dipolog City (Zamboanga del Norte)
4,31 Jan 2017 - 05:19 AM,13.72,120.56,117,2.3,015 km S 33° W,Calatagan (Batangas)
5,31 Jan 2017 - 04:32 AM,5.20,126.10,55,3.2,074 km S 69° E,Sarangani (Davao Occidental)
6,31 Jan 2017 - 02:34 AM,9.98,122.24,19,2.7,042 km N 89° W,Cauayan (Negros Occidental)
7,30 Jan 2017 - 11:19 PM,5.91,125.29,18,1.8,007 km S 05° E,Malapatan (Sarangani)
8,30 Jan 2017 - 11:16 PM,9.87,124.12,34,2.0,006 km S 28° E,Sagbayan (Bohol)
9,30 Jan 2017 - 10:33 PM,13.52,124.58,20,2.5,028 km S 56° E,Baras (Catanduanes)

#Feb 2017

In [24]:
import re
import pandas as pd

x  = "/content/2017feb.txt"
y = "phivolcs_earthquakes_2017_02_Febuary.csv"

#patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

records = []
state = 0#for header
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        if state == 0:
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue
        if state == 1:# latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue
        if state == 2:# longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0#reset here after format break
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:#magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:#location
            cur["Location"] = line
            records.append(cur)
            state = 0
            cur = {}


df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])


for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
#--separation
df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]
#---

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())

#----save---#
df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {OUTPUT_FILE}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Data Saved: 383 rows → phivolcs_earthquakes(2017_January).csv

In [25]:
df.head(10)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,28 Feb 2017 - 11:26 PM,14.05,120.42,116,2.4,022 km S 81° W,Nasugbu (Batangas)
1,28 Feb 2017 - 11:15 PM,6.22,125.24,106,2.4,005 km S 15° W,Malungon (Sarangani)
2,28 Feb 2017 - 11:00 PM,17.90,120.78,14,3.5,039 km S 31° E,Laoag City
3,28 Feb 2017 - 09:36 PM,13.52,124.39,15,2.2,019 km S 67° E,Virac (Catanduanes)
4,28 Feb 2017 - 07:56 PM,4.51,125.57,14,2.5,103 km S 06° E,Sarangani (Davao Occidental)
5,28 Feb 2017 - 01:02 PM,4.53,127.21,84,3.5,217 km S 62° E,Sarangani (Davao Occidental)
6,28 Feb 2017 - 11:26 AM,12.16,125.87,17,3.3,039 km S 86° E,San Policarpo (Eastern Samar)
7,28 Feb 2017 - 05:43 AM,18.62,121.20,14,2.8,013 km N 86° E,Claveria (Cagayan)
8,28 Feb 2017 - 05:18 AM,16.87,120.19,16,2.3,023 km N 46° W,Bacnotan (La Union)
9,28 Feb 2017 - 03:44 AM,13.94,120.43,88,2.1,025 km N 62° W,Calatagan (Batangas)

#Mar 2017

In [26]:
import re
import pandas as pd

x  = "/content/2017mar.txt"
y = "phivolcs_earthquakes_2017_03_March.csv"

#patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

records = []
state = 0#for header
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        if state == 0:
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue
        if state == 1:# latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue
        if state == 2:# longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0#reset here after format break
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:#magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:#location
            cur["Location"] = line
            records.append(cur)
            state = 0
            cur = {}


df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])


for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
#--separation
df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]
#---

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())

#----save---#
df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {OUTPUT_FILE}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Data Saved: 366 rows → phivolcs_earthquakes(2017_January).csv

In [27]:
df.head(10)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 Mar 2017 - 08:53 PM,9.80,122.51,30,2.5,009 km S 81° W,Candoni (Negros Occidental)
1,31 Mar 2017 - 08:25 PM,9.97,126.23,11,3.1,016 km N 78° E,San Isidro (Surigao del Norte)
2,31 Mar 2017 - 07:00 PM,13.60,120.24,5,2.7,014 km S 06° W,Looc (Occidental Mindoro)
3,31 Mar 2017 - 06:52 PM,19.78,120.25,43,4.4,139 km N 67° W,Calayan (Cagayan)
4,31 Mar 2017 - 06:29 PM,12.95,124.67,24,2.1,051 km N 34° W,Pambujan (Northern Samar)
5,31 Mar 2017 - 06:08 PM,10.21,125.49,31,2.1,020 km S 30° W,Loreto (Dinagat)
6,31 Mar 2017 - 05:15 PM,8.66,122.75,13,2.4,041 km N 68° W,Manukan (Zamboanga del Norte)
7,31 Mar 2017 - 04:32 PM,16.61,119.95,22,2.0,025 km N 15° E,Bolinao (Pangasinan)
8,31 Mar 2017 - 04:29 PM,13.04,124.67,34,2.0,044 km S 88° E,Prieto Diaz (Sorsogon)
9,31 Mar 2017 - 01:44 PM,13.73,120.57,127,2.8,013 km S 30° W,Calatagan (Batangas)

#April 2017

In [61]:
import re
import pandas as pd

x  = "/content/2017apr.txt"
y = "phivolcs_earthquakes_2017_04_April.csv"

#patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

records = []
state = 0#for header
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        if state == 0:
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue
        if state == 1:# latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue
        if state == 2:# longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0#reset here after format break
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:#magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            if line:  # only save non-empty
              cur["Location"] = line
              records.append(cur)
              state = 0
              cur = {}


df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])


for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
#--separation
df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]
#---

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())

#----save---#
df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {OUTPUT_FILE}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         7
dtype: int64
Data Saved: 939 rows → phivolcs_earthquakes(2017_January).csv

In [62]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
133,25 Apr 2017 - 04:56 AM,11.90,124.05,1,3.0,014 km S 25° E Cataingan (Masbate),None
134,25 Apr 2017 - 02:48 AM,9.44,125.63,19,2.6,007 km S 68° E Kitcharao (Agusan Del Norte),None
135,25 Apr 2017 - 02:35 AM,13.90,120.86,28,2.4,008 km N 52° W San Luis (Batangas),None
136,25 Apr 2017 - 12:34 AM,6.22,123.65,19,3.6,060 km S 49° W Kalamansig (Sultan Kudarat),None
137,24 Apr 2017 - 11:40 PM,14.58,120.05,45,2.0,027 km S 63° W Morong (Bataan),None
138,24 Apr 2017 - 11:18 PM,8.41,126.68,33,2.7,038 km N 84° E Hinatuan (Surigao Del Sur),None
176,22 Apr 2017 - 08:44 PM,9.88,125.50,25,2.8,010 km N 05° E Surigao City (Surigao Del Norte),None

In [64]:
df.at[133, "Coordinates"] = "014 km S 25° E"
df.at[133, "Location"] = "Cataingan (Masbate)"

df.at[134, "Coordinates"] = "007 km S 68° E"
df.at[134, "Location"] = "Kitcharao (Agusan Del Norte)"

df.at[135, "Coordinates"] = "008 km N 52° W"
df.at[135, "Location"] = "San Luis (Batangas)"

df.at[136, "Coordinates"] = "060 km S 49° W"
df.at[136, "Location"] = "Kalamansig (Sultan Kudarat)"

df.at[137, "Coordinates"] = "027 km S 63° W"
df.at[137, "Location"] = "Morong (Bataan)"

df.at[138, "Coordinates"] = "038 km N 84° E"
df.at[138, "Location"] = "Hinatuan (Surigao Del Sur)"


df.at[176, "Coordinates"] = "010 km N 05° E"
df.at[176, "Location"] = "Surigao City (Surigao Del Norte)"

In [67]:

df.to_csv("phivolcs_earthquakes_2017_04_April.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())

Data Saved: 939 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Apr 2017 - 11:42 PM,5.66,125.11,3,2.0,024 km S 28° E,Maasim (Sarangani)
1,30 Apr 2017 - 10:51 PM,9.73,122.18,27,3.4,025 km S 83° W,Sipalay (Negros Occidental)
2,30 Apr 2017 - 10:45 PM,7.45,124.50,71,2.0,023 km S 80° W,Banisilan (North Cotabato)
3,30 Apr 2017 - 10:33 PM,7.58,124.66,4,2.3,013 km S 57° W,Wao (Lanao Del Sur)
4,30 Apr 2017 - 10:01 PM,5.80,125.07,6,2.9,010 km S 44° E,Maasim (Sarangani)

#May 2017

In [68]:
import re
import pandas as pd

x  = "/content/2017may.txt"
y = "phivolcs_earthquakes_2017_05_May.csv"

#patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

records = []
state = 0#for header
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        if state == 0:
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue
        if state == 1:# latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue
        if state == 2:# longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0#reset here after format break
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:#magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            if line:
              cur["Location"] = line
              records.append(cur)
              state = 0
              cur = {}


df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])


for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
#--separation
df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]
#---

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())

#----save---#
df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {OUTPUT_FILE}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Data Saved: 583 rows → phivolcs_earthquakes(2017_January).csv

In [69]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [70]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 May 2017 - 11:19 PM,7.69,124.65,3,3.3,013 km N 65° W,Wao (Lanao Del Sur)
1,31 May 2017 - 10:27 PM,13.57,121.65,27,2.0,024 km N 57° W,Boac (Marinduque)
2,31 May 2017 - 09:40 PM,13.01,124.52,35,2.0,036 km S 83° E,Prieto Diaz (Sorsogon)
3,31 May 2017 - 09:15 PM,11.17,121.60,20,2.5,048 km N 87° W,Laua-an (Antique)
4,31 May 2017 - 07:22 PM,11.01,125.59,25,3.0,015 km S 81° E,Guiuan (Eastern Samar)
5,31 May 2017 - 05:55 PM,4.69,126.14,123,3.7,110 km S 42° E,Sarangani (Davao Occidental)
6,31 May 2017 - 10:26 AM,5.89,123.95,568,3.7,045 km S 37° W,Palimbag (Sultan Kudarat)
7,31 May 2017 - 09:33 AM,5.72,125.05,22,2.5,016 km S 15° E,Maasim (Sarangani)
8,31 May 2017 - 08:37 AM,5.58,124.97,17,2.1,031 km S 07° W,Maasim (Sarangani)
9,31 May 2017 - 08:05 AM,9.73,124.54,24,2.2,004 km S 63° W,Anda (Bohol)
10,31 May 2017 - 07:17 AM,5.73,127.26,109,3.4,166 km S 52° E,Governor Generoso (Davao Oriental)
11,31 May 2017 - 06:33 AM,6.13,126.27,128,2.8,061 km S 20° E,Governor Generoso (Davao Oriental)
12,31 May 2017 - 02:37 AM,7.78,126.76,30,2.8,034 km S 88° E,Cateel (Davao Oriental)
13,31 May 2017 - 01:47 AM,12.98,124.74,9,1.8,059 km S 82° E,Prieto Diaz (Sorsogon)
14,31 May 2017 - 01:18 AM,15.66,120.23,8,2.3,015 km S 66° W,San Clemente (Tarlac)
15,31 May 2017 - 12:50 AM,13.60,120.98,33,2.1,017 km S 13° E,Mabini (Batangas)
16,31 May 2017 - 12:49 AM,13.49,120.99,32,2.0,029 km S 11° E,Mabini (Batangas)
17,31 May 2017 - 12:35 AM,12.85,123.74,35,2.1,032 km S 02° E,Legazpi City (Albay)
18,30 May 2017 - 11:39 PM,6.84,127.06,11,2.7,072 km S 71° E,Tarragona (Davao Oriental)
19,30 May 2017 - 11:32 PM,13.88,120.50,19,1.9,015 km N 68° W,Calatagan (Batangas)

In [ ]:
'''
df.at[133, "Coordinates"] = "014 km S 25° E"
df.at[133, "Location"] = "Cataingan (Masbate)"
'''

In [ ]:
'''
df.to_csv("phivolcs_earthquakes_2017_04_April.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())
'''

Data Saved: 939 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Apr 2017 - 11:42 PM,5.66,125.11,3,2.0,024 km S 28° E,Maasim (Sarangani)
1,30 Apr 2017 - 10:51 PM,9.73,122.18,27,3.4,025 km S 83° W,Sipalay (Negros Occidental)
2,30 Apr 2017 - 10:45 PM,7.45,124.50,71,2.0,023 km S 80° W,Banisilan (North Cotabato)
3,30 Apr 2017 - 10:33 PM,7.58,124.66,4,2.3,013 km S 57° W,Wao (Lanao Del Sur)
4,30 Apr 2017 - 10:01 PM,5.80,125.07,6,2.9,010 km S 44° E,Maasim (Sarangani)

#June 2017

In [71]:
import re
import pandas as pd

x  = "/content/2017jun.txt"
y = "phivolcs_earthquakes_2017_06_June.csv"

#patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

records = []
state = 0#for header
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        if state == 0:
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue
        if state == 1:# latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue
        if state == 2:# longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0#reset here after format break
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:#magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            if line:
              cur["Location"] = line
              records.append(cur)
              state = 0
              cur = {}


df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])


for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
#--separation
df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]
#---

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())

#----save---#
df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {OUTPUT_FILE}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         2
dtype: int64
Data Saved: 408 rows → phivolcs_earthquakes(2017_January).csv

In [72]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
231,14 Jun 2017 - 11:24 PM,10.69,125.00,1,2.9,006 km S 17° W Abuyog (Leyte),None
338,07 Jun 2017 - 07:21 PM,5.09,127.62,85,3.1,239 km S 68° E oF Jose Abad Santos (Davao Occi...,None

In [76]:

df.at[231	, "Coordinates"] = "006 km S 17° W"
df.at[231	, "Location"] = "Abuyog (Leyte)"

df.at[338	, "Coordinates"] = "239 km S 68° E"
df.at[338	, "Location"] = "Jose Abad Santos (Davao Occidental)"

In [77]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [78]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Jun 2017 - 11:34 PM,11.06,121.84,22,2.0,020 km N 51° W,Patnongon (Antique)
1,30 Jun 2017 - 06:57 PM,17.87,120.40,21,2.4,006 km S 88° W,Sinait (Ilocos Norte)
2,30 Jun 2017 - 12:17 PM,13.59,119.98,32,2.4,032 km S 64° W,Looc (Occidental Mindoro)
3,30 Jun 2017 - 11:39 AM,10.02,124.15,2,2.9,010 km N 44° W,Danao (Bohol)
4,30 Jun 2017 - 10:39 AM,19.93,121.74,24,2.5,047 km S 17° W,Sabtang (Batanes)
5,30 Jun 2017 - 08:44 AM,6.45,123.72,1,3.3,040 km S 69° W,Kalamansig (Sultan Kudarat)
6,30 Jun 2017 - 07:32 AM,16.56,120.46,17,2.4,005 km N 24° E,Burgos (La Union)
7,30 Jun 2017 - 02:48 AM,8.11,126.00,20,2.5,007 km S 20° E,Bunawan (Agusan Del Sur)
8,30 Jun 2017 - 02:06 AM,18.01,120.05,28,2.7,046 km N 79° W,Badoc (Ilocos Norte)
9,30 Jun 2017 - 12:34 AM,15.05,120.16,69,2.2,009 km N 03° E,San Marcelino (Zambales)
10,30 Jun 2017 - 12:17 AM,16.55,120.42,18,4.0,003 km N 57° E,Naguilian (La Union)
11,30 Jun 2017 - 12:06 AM,20.13,121.35,33,3.6,059 km S 67° W,Sabtang (Batanes)
12,29 Jun 2017 - 11:57 PM,19.05,120.85,1,2.5,055 km N 26° W,Claveria (Cagayan)
13,29 Jun 2017 - 06:33 PM,5.65,125.60,123,4.0,027 km N 31° E,Sarangani (Davao Occidental)
14,29 Jun 2017 - 05:06 PM,7.13,126.59,117,3.2,011 km S 30° E,Manay (Davao Oriental)
15,29 Jun 2017 - 04:31 PM,7.24,126.56,133,2.8,004 km N 34° E,Manay (Davao Oriental)
16,29 Jun 2017 - 11:50 AM,13.93,120.48,5,2.3,019 km N 59° W,Calatagan (Batangas)
17,29 Jun 2017 - 07:45 AM,8.50,126.89,22,3.9,062 km N 76° E,Hinatuan (Surigao Del Sur)
18,29 Jun 2017 - 04:37 AM,8.50,127.16,20,4.0,092 km N 81° E,Hinatuan (Surigao Del Sur)
19,29 Jun 2017 - 02:58 AM,13.93,120.53,1,2.2,016 km N 44° W,Calatagan (Batangas)

In [79]:

df.to_csv("phivolcs_earthquakes_2017_06_June.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())

Data Saved: 408 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Jun 2017 - 11:34 PM,11.06,121.84,22,2.0,020 km N 51° W,Patnongon (Antique)
1,30 Jun 2017 - 06:57 PM,17.87,120.40,21,2.4,006 km S 88° W,Sinait (Ilocos Norte)
2,30 Jun 2017 - 12:17 PM,13.59,119.98,32,2.4,032 km S 64° W,Looc (Occidental Mindoro)
3,30 Jun 2017 - 11:39 AM,10.02,124.15,2,2.9,010 km N 44° W,Danao (Bohol)
4,30 Jun 2017 - 10:39 AM,19.93,121.74,24,2.5,047 km S 17° W,Sabtang (Batanes)

#July 2017 (added condition)

In [93]:
import re
import pandas as pd

x  = "/content/2017jul.txt"
y = "phivolcs_earthquakes_2017_07_July.csv"

#added patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

#added
row_rx = re.compile(
    r"^(?P<datetime>\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM))\s+"
    r"(?P<lat>\d{1,2}\.\d{2})\s+"
    r"(?P<long>\d{1,3}\.\d{2})\s+"
    r"(?P<depth>\d+)\s+"
    r"(?P<mag>\d+\.\d)$"
)

records = []
state = 0
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        m = row_rx.match(line)
        if m:
            cur = {
                "Date - Time (Philippine Time)": m.group("datetime"),
                "Latitude (ºN)": m.group("lat"),
                "Longitude (ºE)": m.group("long"),
                "Depth (km)": m.group("depth"),
                "Mag": m.group("mag"),
            }
            state = 5
            continue


        if state == 0:  # datetime
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue

        if state == 1:  # latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue

        if state == 2:  # longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:  # magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            cur["Location"] = line if line else None
            records.append(cur)
            state = 0
            cur = {}

df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])

for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())


df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {y}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Data Saved: 521 rows → phivolcs_earthquakes_2017_07_July.csv

In [94]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [95]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 Jul 2017 - 11:52 PM,8.05,126.29,95,3.5,013 km N 85° W,Lingig (Surigao Del Sur)
1,31 Jul 2017 - 11:42 PM,13.20,124.08,28,1.8,005 km N 72° W,Rapu-rapu (Albay)
2,31 Jul 2017 - 11:27 PM,8.05,127.06,12,3.4,071 km N 89° E,Lingig (Surigao Del Sur)
3,31 Jul 2017 - 06:44 PM,8.73,126.60,33,2.7,035 km S 76° E,Marihatag (Surigao Del Sur)
4,31 Jul 2017 - 11:14 AM,9.87,125.44,27,2.3,011 km N 35° W,Surigao City (Surigao Del Norte)
5,31 Jul 2017 - 06:57 AM,14.04,123.89,28,2.0,026 km N 51° E,Garchitorena (Camarines Sur)
6,31 Jul 2017 - 01:13 AM,17.36,120.35,12,2.6,010 km N 71° W,San Esteban (Ilocos Sur)
7,30 Jul 2017 - 11:30 PM,13.06,123.98,7,3.1,010 km N 13° W,Sorsogon (Sorsogon)
8,30 Jul 2017 - 10:56 PM,9.90,126.15,14,2.9,008 km S 60° E,San Isidro (Surigao Del Norte)
9,30 Jul 2017 - 08:28 PM,5.50,126.39,196,2.7,095 km S 64° E,Jose Abad Santos (Davao Occidental)
10,30 Jul 2017 - 06:32 PM,15.01,119.89,8,2.6,021 km S 75° W,San Felipe (Zambales)
11,30 Jul 2017 - 06:29 PM,15.00,119.87,10,3.2,022 km S 73° W,San Felipe (Zambales)
12,30 Jul 2017 - 09:32 AM,6.63,125.86,134,3.1,024 km S 85° W,Governor Generoso (Davao Oriental)
13,30 Jul 2017 - 09:09 AM,6.03,125.90,146,3.5,029 km S 52° E,Don Marcelino (Davao Occidental)
14,30 Jul 2017 - 08:27 AM,13.25,120.48,1,2.5,018 km S 04° E,Paluan (Occidental Mindoro)
15,30 Jul 2017 - 05:34 AM,9.00,126.27,33,3.1,003 km N 28° W,Bayabas (Surigao Del Sur)
16,30 Jul 2017 - 02:52 AM,11.18,124.63,5,2.4,008 km S 89° E,Kananga (Leyte)
17,30 Jul 2017 - 01:10 AM,11.24,124.71,6,2.5,005 km S 83° W,Tunga (Leyte)
18,29 Jul 2017 - 08:54 PM,13.61,119.98,21,3.5,032 km S 67° W,Looc (Occidental Mindoro)
19,29 Jul 2017 - 02:31 PM,14.99,119.69,14,3.4,041 km S 78° W,San Felipe (Zambales)

In [96]:
'''
df.at[133, "Coordinates"] = "014 km S 25° E"
df.at[133, "Location"] = "Cataingan (Masbate)"
'''

'\ndf.at[133, "Coordinates"] = "014 km S 25° E"\ndf.at[133, "Location"] = "Cataingan (Masbate)"\n'

In [97]:
'''
df.to_csv("phivolcs_earthquakes_2017_04_April.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())
'''

'\ndf.to_csv("phivolcs_earthquakes_2017_04_April.csv", index=False, encoding="utf-8")\nprint(f"Data Saved: {len(df)} rows")\ndisplay(df.head())\n'

#August 2017 (added condition)

In [98]:
import re
import pandas as pd

x  = "/content/2017aug.txt"
y = "phivolcs_earthquakes_2017_08_August.csv"

#added patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

#added
row_rx = re.compile(
    r"^(?P<datetime>\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM))\s+"
    r"(?P<lat>\d{1,2}\.\d{2})\s+"
    r"(?P<long>\d{1,3}\.\d{2})\s+"
    r"(?P<depth>\d+)\s+"
    r"(?P<mag>\d+\.\d)$"
)

records = []
state = 0
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        m = row_rx.match(line)
        if m:
            cur = {
                "Date - Time (Philippine Time)": m.group("datetime"),
                "Latitude (ºN)": m.group("lat"),
                "Longitude (ºE)": m.group("long"),
                "Depth (km)": m.group("depth"),
                "Mag": m.group("mag"),
            }
            state = 5
            continue


        if state == 0:  # datetime
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue

        if state == 1:  # latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue

        if state == 2:  # longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:  # magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            cur["Location"] = line if line else None
            records.append(cur)
            state = 0
            cur = {}

df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])

for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()
cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())


df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {y}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         6
dtype: int64
Data Saved: 421 rows → phivolcs_earthquakes_2017_08_August.csv

In [99]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
46,29 Aug 2017 - 05:56 PM,6.63,125.82,74,2.7,028 km S 85° W Governor Generoso (Davao Oriental),None
47,29 Aug 2017 - 04:08 PM,13.66,124.86,12,3.0,040 km S 49° E Baras (Catanduanes),None
48,29 Aug 2017 - 04:03 PM,5.29,126.94,14,2.9,161 km S 66° E Jose Abad Santos (Davao Occiden...,None
49,29 Aug 2017 - 02:11 PM,10.08,124.99,17,4.0,016 km S 56° W Liloan (Southern Leyte),None
50,29 Aug 2017 - 06:49 AM,14.89,121.96,14,2.0,005 km N 08° W Burdeos (Quezon),None
114,24 Aug 2017 - 11:10 AM,13.83,119.95,10,2.5,035 km N 71° W Looc (Occidental Mindoro),None

In [104]:
fix = {
    46: {"Coordinates": "028 km S 85° W", "Location": "Governor Generoso (Davao Oriental)"},
    47: {"Coordinates": "040 km S 49° E", "Location": "Baras (Catanduanes)"},
    48: {"Coordinates": "161 km S 66° E", "Location": "Jose Abad Santos (Davao Occidental)"},
    49: {"Coordinates": "016 km S 56° W", "Location": "Liloan (Southern Leyte)"},
    50: {"Coordinates": "005 km N 08° W", "Location": "Burdeos (Quezon)"},
    114: {"Coordinates": "035 km N 71° W", "Location": "Looc (Occidental Mindoro)"}
}

for idx, changes in fix.items():
    for col, val in changes.items():
        df.at[idx, col] = val

In [105]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [106]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 Aug 2017 - 09:55 PM,11.27,124.62,7,3.2,004 km S 46° W,Capoocan (Leyte)
1,31 Aug 2017 - 08:08 PM,13.21,122.43,7,2.7,018 km S 33° W,San Francisco (Aurora) (Quezon)
2,31 Aug 2017 - 07:16 PM,9.76,124.74,1,3.0,018 km N 85° E,Anda (Bohol)
3,31 Aug 2017 - 03:06 PM,15.04,119.88,28,2.0,020 km S 85° W,San Felipe (Zambales)
4,31 Aug 2017 - 08:15 AM,9.86,124.04,5,3.3,004 km N 85° E,Catigbian (Bohol)
5,31 Aug 2017 - 07:44 AM,6.77,123.89,32,1.9,023 km N 55° W,Lebak (Sultan Kudarat)
6,31 Aug 2017 - 06:57 AM,14.34,120.27,56,3.1,026 km S 65° W,Mariveles (Bataan)
7,31 Aug 2017 - 05:47 AM,18.28,122.82,5,2.7,075 km S 76° E,Santa Ana (Cagayan)
8,31 Aug 2017 - 05:24 AM,18.11,120.44,29,2.2,015 km N 65° W,Batac (Ilocos Norte)
9,31 Aug 2017 - 05:06 AM,12.70,123.41,3,2.2,031 km S 42° W,Donsol (Sorsogon)
10,31 Aug 2017 - 04:53 AM,6.97,125.33,26,2.2,023 km N 09° W,Digos City (Davao del Sur)
11,31 Aug 2017 - 03:51 AM,5.03,127.44,30,2.9,223 km S 65° E,Jose Abad Santos (Davao Occidental)
12,31 Aug 2017 - 03:45 AM,10.10,124.33,25,2.3,005 km S 07° E,Talibon (Bohol)
13,31 Aug 2017 - 03:36 AM,6.87,125.13,34,2.5,012 km N 67° W,Digos City (Davao del Sur)
14,31 Aug 2017 - 02:59 AM,6.91,125.32,25,2.4,017 km N 20° W,Digos City (Davao del Sur)
15,31 Aug 2017 - 02:58 AM,6.85,125.28,22,1.8,014 km N 46° W,Digos City (Davao del Sur)
16,31 Aug 2017 - 02:42 AM,6.91,125.33,27,2.3,016 km N 16° W,Digos City (Davao del Sur)
17,31 Aug 2017 - 02:37 AM,6.85,125.37,16,2.4,009 km N 01° E,Digos City (Davao del Sur)
18,31 Aug 2017 - 02:15 AM,11.30,124.55,9,3.8,010 km N 88° W,Capoocan (Leyte)
19,31 Aug 2017 - 01:45 AM,6.85,125.30,22,3.1,011 km N 39° W,Digos City (Davao del Sur)

In [107]:

df.to_csv("phivolcs_earthquakes_2017_08_August.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())

Data Saved: 421 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 Aug 2017 - 09:55 PM,11.27,124.62,7,3.2,004 km S 46° W,Capoocan (Leyte)
1,31 Aug 2017 - 08:08 PM,13.21,122.43,7,2.7,018 km S 33° W,San Francisco (Aurora) (Quezon)
2,31 Aug 2017 - 07:16 PM,9.76,124.74,1,3.0,018 km N 85° E,Anda (Bohol)
3,31 Aug 2017 - 03:06 PM,15.04,119.88,28,2.0,020 km S 85° W,San Felipe (Zambales)
4,31 Aug 2017 - 08:15 AM,9.86,124.04,5,3.3,004 km N 85° E,Catigbian (Bohol)

#September 2017 (added condition)

In [157]:
import re
import pandas as pd

x  = "/content/2017sep.txt"
y = "phivolcs_earthquakes_2017_09_September.csv"

#added patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

#added
row_rx = re.compile(
    r"^(?P<datetime>\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM))\s+"
    r"(?P<lat>\d{1,2}\.\d{2})\s+"
    r"(?P<long>\d{1,3}\.\d{2})\s+"
    r"(?P<depth>\d+)\s+"
    r"(?P<mag>\d+\.\d)$"
)

records = []
state = 0
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        m = row_rx.match(line)
        if m:
            cur = {
                "Date - Time (Philippine Time)": m.group("datetime"),
                "Latitude (ºN)": m.group("lat"),
                "Longitude (ºE)": m.group("long"),
                "Depth (km)": m.group("depth"),
                "Mag": m.group("mag"),
            }
            state = 5
            continue


        if state == 0:  # datetime
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue

        if state == 1:  # latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue

        if state == 2:  # longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:  # magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            cur["Location"] = line if line else None
            records.append(cur)
            state = 0
            cur = {}

df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])

for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")


df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()

cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())


df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {y}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)     0
Latitude (ºN)                     0
Longitude (ºE)                    0
Depth (km)                        0
Mag                               0
Coordinates                       0
Location                         26
dtype: int64
Data Saved: 361 rows → phivolcs_earthquakes_2017_09_September.csv

In [158]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
193,15 Sep 2017 - 10:20 PM,7.73,126.94,16,3.0,046 km N 68° E Baganga (Davao Oriental),None
194,15 Sep 2017 - 05:38 PM,18.40,120.29,26,2.7,039 km N 54° W Laoag City (Ilocos Norte),None
195,15 Sep 2017 - 04:29 PM,14.04,120.35,17,2.1,030 km S 82° W Nasugbu (Batangas),None
196,15 Sep 2017 - 03:44 PM,6.31,126.24,15,3.0,042 km S 26° E Governor Generoso (Davao Oriental),None
197,15 Sep 2017 - 02:51 PM,11.16,124.70,10,3.0,015 km S 80° E Kananga (Leyte),None
198,15 Sep 2017 - 11:11 AM,10.35,125.33,1,2.8,015 km S 71° E Hinunangan (Southern Leyte),None
199,15 Sep 2017 - 07:14 AM,9.38,126.26,49,3.1,014 km N 33° E Cortes (Surigao Del Sur),None
200,15 Sep 2017 - 06:43 AM,16.13,120.16,6,2.9,010 km N 48° E Sual (Pangasinan),None
201,15 Sep 2017 - 04:26 AM,8.90,126.28,35,2.8,003 km S 54° W Cagwait (Surigao Del Sur),None
202,15 Sep 2017 - 03:27 AM,10.97,124.73,1,2.6,007 km N 34° E Albuera (Leyte),None
203,15 Sep 2017 - 03:02 AM,10.37,125.22,4,2.4,004 km S 48° E Hinundayan (Southern Leyte),None
204,14 Sep 2017 - 11:51 PM,5.83,127.06,159,3.2,142 km S 50° E Governor Generoso (Davao Oriental),None
205,14 Sep 2017 - 11:26 PM,6.82,123.66,1,2.4,048 km N 67° W Lebak (Sultan Kudarat),None
206,14 Sep 2017 - 11:10 PM,7.73,121.99,34,2.8,015 km N 79° W Siocon (Zamboanga Del Norte),None
207,14 Sep 2017 - 08:51 PM,13.78,120.54,113,2.8,032 km N 78° E Looc (Occidental Mindoro),None
208,14 Sep 2017 - 12:15 PM,12.76,124.62,26,2.1,026 km N 14° E Bobon (Northern Samar),None
209,14 Sep 2017 - 08:13 AM,18.91,121.21,34,2.4,036 km N 23° E Claveria (Cagayan),None
210,14 Sep 2017 - 05:51 AM,9.95,124.19,12,2.3,004 km N 81° W Danao (Bohol),None
211,14 Sep 2017 - 05:07 AM,13.20,122.61,12,2.2,015 km S 29° W San Andres (Quezon),None
212,14 Sep 2017 - 12:27 AM,9.44,125.53,9,2.7,006 km S 62° W Alegria (Surigao Del Norte),None
213,14 Sep 2017 - 12:26 AM,6.84,123.61,1,2.3,064 km S 72° W Upi (Maguindanao),None
214,13 Sep 2017 - 11:21 PM,15.33,118.89,31,2.1,109 km S 84° W Palauig (Zambales),None
215,13 Sep 2017 - 11:03 PM,12.76,123.56,10,2.7,016 km S 14° W Donsol (Sorsogon),None
216,13 Sep 2017 - 08:05 PM,7.08,125.75,1,2.6,004 km S 86° E Samal (Island Garden City Of Sa...,None
217,13 Sep 2017 - 05:00 PM,12.80,123.60,8,3.8,016 km S 30° W Pilar (Sorsogon),None
218,13 Sep 2017 - 02:41 PM,9.94,125.45,19,2.5,016 km S 82° W Dinagat (Dinagat),None

In [159]:

fix = {
    193: {"Coordinates": "046 km N 68° E", "Location": "Baganga (Davao Oriental)"},
    194: {"Coordinates": "039 km N 54° W", "Location": "Laoag City (Ilocos Norte)"},
    195: {"Coordinates": "030 km S 82° W", "Location": "Nasugbu (Batangas)"},
    196: {"Coordinates": "042 km S 26° E", "Location": "Governor Generoso (Davao Oriental)"},
    197: {"Coordinates": "015 km S 80° E", "Location": "Kananga (Leyte)"},
    198: {"Coordinates": "015 km S 71° E", "Location": "Hinunangan (Southern Leyte)"},
    199: {"Coordinates": "014 km N 33° E", "Location": "Cortes (Surigao Del Sur)"},
    200: {"Coordinates": "010 km N 48° E", "Location": "Sual (Pangasinan)"},
    201: {"Coordinates": "003 km S 54° W", "Location": "Cagwait (Surigao Del Sur)"},
    202: {"Coordinates": "007 km N 34° E", "Location": "Albuera (Leyte)"},
    203: {"Coordinates": "004 km S 48° E", "Location": "Hinundayan (Southern Leyte)"},
    204: {"Coordinates": "142 km S 50° E", "Location": "Governor Generoso (Davao Oriental)"},
    205: {"Coordinates": "048 km N 67° W", "Location": "Lebak (Sultan Kudarat)"},
    206: {"Coordinates": "015 km N 79° W", "Location": "Siocon (Zamboanga Del Norte)"},
    207: {"Coordinates": "032 km N 78° E", "Location": "Looc (Occidental Mindoro)"},
    208: {"Coordinates": "026 km N 14° E", "Location": "Bobon (Northern Samar)"},
    209: {"Coordinates": "036 km N 23° E", "Location": "Claveria (Cagayan)"},
    210: {"Coordinates": "004 km N 81° W", "Location": "Danao (Bohol)"},
    211: {"Coordinates": "015 km S 29° W", "Location": "San Andres (Quezon)"},
    212: {"Coordinates": "006 km S 62° W", "Location": "Alegria (Surigao Del Norte)"},
    213: {"Coordinates": "064 km S 72° W", "Location": "Upi (Maguindanao)"},
    214: {"Coordinates": "109 km S 84° W", "Location": "Palauig (Zambales)"},
    215: {"Coordinates": "016 km S 14° W", "Location": "Donsol (Sorsogon)"},
    216: {"Coordinates": "004 km S 86° E", "Location": "Samal (Island Garden City Of Samal)"},
    217: {"Coordinates": "016 km S 30° W", "Location": "Pilar (Sorsogon)"},
    218: {"Coordinates": "016 km S 82° W", "Location": "Dinagat (Dinagat)"}
}


for idx, changes in fix.items():
    for col, val in changes.items():
        df.at[idx, col] = val

In [160]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [161]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Sep 2017 - 09:42 PM,9.60,123.23,18,2.2,009 km N 70° W,Ginatilan (Cebu)
1,30 Sep 2017 - 10:45 AM,7.19,126.63,28,2.8,011 km S 75° E,Manay (Davao Oriental)
2,30 Sep 2017 - 07:18 AM,13.63,120.52,78,3.2,025 km S 30° W,Calatagan (Batangas)
3,30 Sep 2017 - 02:00 AM,8.46,124.83,2,3.2,010 km S 32° W,Malitbog (Bukidnon)
4,30 Sep 2017 - 01:12 AM,7.53,124.74,1,2.5,013 km S 07° W,Wao (Lanao del Sur)
5,30 Sep 2017 - 12:51 AM,9.41,126.14,18,2.8,016 km N 23° W,Cortes (Surigao del Sur)
6,30 Sep 2017 - 12:46 AM,7.66,124.74,1,3.4,002 km N 34° W,Wao (Lanao Del Sur)
7,29 Sep 2017 - 06:16 PM,6.10,124.95,16,2.3,018 km N 39° W,Polomok (South Cotabato)
8,29 Sep 2017 - 04:03 PM,9.62,125.42,1,2.6,002 km N82° W,Malimono (Surigao Del Norte)
9,29 Sep 2017 - 03:40 PM,9.98,122.88,32,2.1,007 km S 85° E,Kabankalan City (Negros Occidental)
10,29 Sep 2017 - 03:27 PM,18.67,120.40,33,2.1,037 km N 48° E,Santa Ana (Cagayan)
11,29 Sep 2017 - 02:46 PM,13.72,120.94,104,2.4,004 km S 03° E,Mabini (Batangas)
12,29 Sep 2017 - 12:12 PM,18.41,122.44,18,2.6,032 km S 83° E,Santa Ana (Cagayan)
13,29 Sep 2017 - 11:15 AM,16.59,120.00,29,2.0,025 km N 28° E,Bolinao (Pangasinan)
14,29 Sep 2017 - 11:13 AM,17.47,120.21,16,2.3,020 km S 52° W,Santa Catalina (Ilocos Sur)
15,29 Sep 2017 - 09:26 AM,15.51,120.66,33,2.0,007 km S 13° W,Victoria (Tarlac)
16,29 Sep 2017 - 09:14 AM,9.88,124.59,4,2.1,008 km N 80° E,Mabini (Bohol)
17,29 Sep 2017 - 08:03 AM,11.30,124.61,3,2.7,005 km N 81° W,Capoocan (Leyte)
18,29 Sep 2017 - 06:30 AM,9.74,124.07,33,2.0,005 km N 37° W,Bilar (Bohol)
19,29 Sep 2017 - 05:08 AM,18.07,119.29,32,2.7,126 km N 65° W,Santa Catalina (Ilocos Sur)

In [162]:

df.to_csv("phivolcs_earthquakes_2017_09_September.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())

Data Saved: 361 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Sep 2017 - 09:42 PM,9.60,123.23,18,2.2,009 km N 70° W,Ginatilan (Cebu)
1,30 Sep 2017 - 10:45 AM,7.19,126.63,28,2.8,011 km S 75° E,Manay (Davao Oriental)
2,30 Sep 2017 - 07:18 AM,13.63,120.52,78,3.2,025 km S 30° W,Calatagan (Batangas)
3,30 Sep 2017 - 02:00 AM,8.46,124.83,2,3.2,010 km S 32° W,Malitbog (Bukidnon)
4,30 Sep 2017 - 01:12 AM,7.53,124.74,1,2.5,013 km S 07° W,Wao (Lanao del Sur)

#October 2017 (added condition)

In [141]:
import re
import pandas as pd

x  = "/content/2017oct.txt"
y = "phivolcs_earthquakes_2017_10_October.csv"

#added patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

#added
row_rx = re.compile(
    r"^(?P<datetime>\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM))\s+"
    r"(?P<lat>\d{1,2}\.\d{2})\s+"
    r"(?P<long>\d{1,3}\.\d{2})\s+"
    r"(?P<depth>\d+)\s+"
    r"(?P<mag>\d+\.\d)$"
)

records = []
state = 0
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        m = row_rx.match(line)
        if m:
            cur = {
                "Date - Time (Philippine Time)": m.group("datetime"),
                "Latitude (ºN)": m.group("lat"),
                "Longitude (ºE)": m.group("long"),
                "Depth (km)": m.group("depth"),
                "Mag": m.group("mag"),
            }
            state = 5
            continue


        if state == 0:  # datetime
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue

        if state == 1:  # latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue

        if state == 2:  # longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:  # magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            cur["Location"] = line if line else None
            records.append(cur)
            state = 0
            cur = {}

df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])

for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")


df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()

cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())


df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {y}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Data Saved: 330 rows → phivolcs_earthquakes_2017_10_October.csv

In [142]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [143]:
'''
fix = {
    193: {"Coordinates": "046 km N 68° E", "Location": "Baganga (Davao Oriental)"},
    194: {"Coordinates": "039 km N 54° W", "Location": "Laoag City (Ilocos Norte)"},
    195: {"Coordinates": "030 km S 82° W", "Location": "Nasugbu (Batangas)"},
    196: {"Coordinates": "042 km S 26° E", "Location": "Governor Generoso (Davao Oriental)"},
    197: {"Coordinates": "015 km S 80° E", "Location": "Kananga (Leyte)"},
    198: {"Coordinates": "015 km S 71° E", "Location": "Hinunangan (Southern Leyte)"},
    199: {"Coordinates": "014 km N 33° E", "Location": "Cortes (Surigao Del Sur)"},
    200: {"Coordinates": "010 km N 48° E", "Location": "Sual (Pangasinan)"},
    201: {"Coordinates": "003 km S 54° W", "Location": "Cagwait (Surigao Del Sur)"},
    202: {"Coordinates": "007 km N 34° E", "Location": "Albuera (Leyte)"},
    203: {"Coordinates": "004 km S 48° E", "Location": "Hinundayan (Southern Leyte)"},
    204: {"Coordinates": "142 km S 50° E", "Location": "Governor Generoso (Davao Oriental)"},
    205: {"Coordinates": "048 km N 67° W", "Location": "Lebak (Sultan Kudarat)"},
    206: {"Coordinates": "015 km N 79° W", "Location": "Siocon (Zamboanga Del Norte)"},
    207: {"Coordinates": "032 km N 78° E", "Location": "Looc (Occidental Mindoro)"},
    208: {"Coordinates": "026 km N 14° E", "Location": "Bobon (Northern Samar)"},
    209: {"Coordinates": "036 km N 23° E", "Location": "Claveria (Cagayan)"},
    210: {"Coordinates": "004 km N 81° W", "Location": "Danao (Bohol)"},
    211: {"Coordinates": "015 km S 29° W", "Location": "San Andres (Quezon)"},
    212: {"Coordinates": "006 km S 62° W", "Location": "Alegria (Surigao Del Norte)"},
    213: {"Coordinates": "064 km S 72° W", "Location": "Upi (Maguindanao)"},
    214: {"Coordinates": "109 km S 84° W", "Location": "Palauig (Zambales)"},
    215: {"Coordinates": "016 km S 14° W", "Location": "Donsol (Sorsogon)"},
    216: {"Coordinates": "004 km S 86° E", "Location": "Samal (Island Garden City Of Samal)"},
    217: {"Coordinates": "016 km S 30° W", "Location": "Pilar (Sorsogon)"},
    218: {"Coordinates": "016 km S 82° W", "Location": "Dinagat (Dinagat)"}
}


for idx, changes in fix.items():
    for col, val in changes.items():
        df.at[idx, col] = val

'''

'\nfix = {\n    193: {"Coordinates": "046 km N 68° E", "Location": "Baganga (Davao Oriental)"},\n    194: {"Coordinates": "039 km N 54° W", "Location": "Laoag City (Ilocos Norte)"},\n    195: {"Coordinates": "030 km S 82° W", "Location": "Nasugbu (Batangas)"},\n    196: {"Coordinates": "042 km S 26° E", "Location": "Governor Generoso (Davao Oriental)"},\n    197: {"Coordinates": "015 km S 80° E", "Location": "Kananga (Leyte)"},\n    198: {"Coordinates": "015 km S 71° E", "Location": "Hinunangan (Southern Leyte)"},\n    199: {"Coordinates": "014 km N 33° E", "Location": "Cortes (Surigao Del Sur)"},\n    200: {"Coordinates": "010 km N 48° E", "Location": "Sual (Pangasinan)"},\n    201: {"Coordinates": "003 km S 54° W", "Location": "Cagwait (Surigao Del Sur)"},\n    202: {"Coordinates": "007 km N 34° E", "Location": "Albuera (Leyte)"},\n    203: {"Coordinates": "004 km S 48° E", "Location": "Hinundayan (Southern Leyte)"},\n    204: {"Coordinates": "142 km S 50° E", "Location": "Governor Generoso (Davao Oriental)"},\n    205: {"Coordinates": "048 km N 67° W", "Location": "Lebak (Sultan Kudarat)"},\n    206: {"Coordinates": "015 km N 79° W", "Location": "Siocon (Zamboanga Del Norte)"},\n    207: {"Coordinates": "032 km N 78° E", "Location": "Looc (Occidental Mindoro)"},\n    208: {"Coordinates": "026 km N 14° E", "Location": "Bobon (Northern Samar)"},\n    209: {"Coordinates": "036 km N 23° E", "Location": "Claveria (Cagayan)"},\n    210: {"Coordinates": "004 km N 81° W", "Location": "Danao (Bohol)"},\n    211: {"Coordinates": "015 km S 29° W", "Location": "San Andres (Quezon)"},\n    212: {"Coordinates": "006 km S 62° W", "Location": "Alegria (Surigao Del Norte)"},\n    213: {"Coordinates": "064 km S 72° W", "Location": "Upi (Maguindanao)"},\n    214: {"Coordinates": "109 km S 84° W", "Location": "Palauig (Zambales)"},\n    215: {"Coordinates": "016 km S 14° W", "Location": "Donsol (Sorsogon)"},\n    216: {"Coordinates": "004 km S 86° E", "Location": "Samal (Island Garden City Of Samal)"},\n    217: {"Coordinates": "016 km S 30° W", "Location": "Pilar (Sorsogon)"},\n    218: {"Coordinates": "016 km S 82° W", "Location": "Dinagat (Dinagat)"}\n}\n\n\nfor idx, changes in fix.items():\n    for col, val in changes.items():\n        df.at[idx, col] = val\n\n'

In [144]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [145]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 Oct 2017 - 11:35 PM,5.54,126.54,107,3.2,110 km S 69° E,Jose Abad Santos (Davao Occidental)
1,31 Oct 2017 - 10:25 PM,12.94,124.60,23,2.2,038 km N 42° E,Biri (Northern Samar)
2,31 Oct 2017 - 09:12 PM,13.09,120.87,1,2.3,016 km N 83° E,Santa Cruz (Occidental Mindoro)
3,31 Oct 2017 - 06:14 PM,8.54,123.87,8,2.6,026 km S 78° E,Dipolog City
4,31 Oct 2017 - 03:45 PM,16.90,120.24,25,2.6,015 km N 72° W,Luna (La Union)
5,31 Oct 2017 - 11:14 AM,14.59,124.00,19,4.5,062 km N 17° W,Pandan (Cataduanes)
6,31 Oct 2017 - 11:11 AM,3.79,126.39,113,4.3,209 km S 29° E,Sarangani (Davao Occidental)
7,31 Oct 2017 - 04:51 AM,4.88,124.37,105,3.2,126 km S 13° W,Kiamba (Sarangani)
8,31 Oct 2017 - 01:49 AM,13.80,120.55,122,3.0,010 km S 70° W,Calatagan (Batangas)
9,31 Oct 2017 - 01:25 AM,13.72,120.52,93,3.1,017 km S 45° W,Calatagan (Batangas)
10,30 Oct 2017 - 04:07 PM,19.04,121.30,9,2.0,032 km S 33° W,Calayan (Cagayan)
11,30 Oct 2017 - 02:46 PM,9.96,126.25,11,2.7,018 km N 80° E,San Isidro (Surigao Del Norte)
12,30 Oct 2017 - 02:11 PM,10.43,126.35,32,3.7,055 km N 34° E,Burgos (Surigao Del Norte)
13,30 Oct 2017 - 09:15 AM,15.09,120.04,22,2.1,004 km N 44° W,San Felipe (Zambales)
14,30 Oct 2017 - 07:10 AM,9.33,126.32,29,2.6,016 km N 66° E,Cortes (Surigao Del Sur)
15,30 Oct 2017 - 05:37 AM,5.88,127.31,102,3.0,160 km S 58° E,Governor Generoso (Davao Oriental)
16,30 Oct 2017 - 05:01 AM,13.84,120.52,115,4.1,012 km N 84° W,Calatagan (Batangas)
17,30 Oct 2017 - 02:26 AM,15.15,122.33,23,2.4,048 km N 06° W,Jomalig (Quezon)
18,30 Oct 2017 - 01:09 AM,19.04,121.11,4,2.8,045 km S 54° W,Calayan (Cagayan)
19,30 Oct 2017 - 12:32 AM,5.83,127.10,129,3.1,146 km S 51° E,Governor Generoso (Davao Oriental)

In [146]:
'''
df.to_csv("phivolcs_earthquakes_2017_09_September.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())
'''

'\ndf.to_csv("phivolcs_earthquakes_2017_09_September.csv", index=False, encoding="utf-8")\nprint(f"Data Saved: {len(df)} rows")\ndisplay(df.head())\n'

#November2017 (added condition)

In [163]:
import re
import pandas as pd

x  = "/content/2017nov.txt"
y = "phivolcs_earthquakes_2017_11_November.csv"

#added patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

#added
row_rx = re.compile(
    r"^(?P<datetime>\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM))\s+"
    r"(?P<lat>\d{1,2}\.\d{2})\s+"
    r"(?P<long>\d{1,3}\.\d{2})\s+"
    r"(?P<depth>\d+)\s+"
    r"(?P<mag>\d+\.\d)$"
)

records = []
state = 0
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        m = row_rx.match(line)
        if m:
            cur = {
                "Date - Time (Philippine Time)": m.group("datetime"),
                "Latitude (ºN)": m.group("lat"),
                "Longitude (ºE)": m.group("long"),
                "Depth (km)": m.group("depth"),
                "Mag": m.group("mag"),
            }
            state = 5
            continue


        if state == 0:  # datetime
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue

        if state == 1:  # latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue

        if state == 2:  # longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:  # magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            cur["Location"] = line if line else None
            records.append(cur)
            state = 0
            cur = {}

df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])

for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")


df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()

cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())


df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {y}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         4
dtype: int64
Data Saved: 382 rows → phivolcs_earthquakes_2017_11_November.csv

In [164]:
df[df.isnull().any(axis=1)]

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
216,12 Nov 2017 - 01:08 PM,13.85,120.01,33,2.0,004 km S 71° E Santa Teresita (Batangas),None
217,12 Nov 2017 - 12:39 PM,19.19,121.13,28,3.1,036 km S 74° W Calayan (Cagayan),None
218,12 Nov 2017 - 12:29 PM,13.53,123.66,13,2.7,021 km N 55° E Buhi (Camarines Sur),None
219,12 Nov 2017 - 09:52 AM,16.81,122.61,13,2.5,033 km S 34° E Palanan (Isabela),None

In [165]:

fix = {
    216: {"Coordinates": "004 km S 71° E", "Location": "Santa Teresita (Batangas)"},
    217: {"Coordinates": "036 km S 74° W", "Location": "Calayan (Cagayan)"},
    218: {"Coordinates": "021 km N 55° E", "Location": "Buhi (Camarines Sur)"},
    219: {"Coordinates": "033 km S 34° E", "Location": "Palanan (Isabela)"},

}


for idx, changes in fix.items():
    for col, val in changes.items():
        df.at[idx, col] = val

In [166]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [167]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Nov 2017 - 11:15 PM,10.10,123.38,4,2.3,002 km S 16° E,Guihulngan (Negros Oriental)
1,30 Nov 2017 - 09:50 PM,9.40,122.54,20,2.4,011 km S 85° W,Basay (Negros Oriental)
2,30 Nov 2017 - 09:38 PM,14.95,123.97,21,2.3,102 km N 12° W,Pandan (Catanduanes)
3,30 Nov 2017 - 09:15 PM,3.61,125.67,185,3.3,203 km S 06° E,Sarangani (Davao Occidental)
4,30 Nov 2017 - 08:54 PM,18.31,120.46,30,2.3,017 km S 81° W,Pasuquin (Ilocos Norte)
5,30 Nov 2017 - 08:52 PM,8.05,126.48,11,2.4,007 km N 81° E,Lingig (Surigao Del Sur)
6,30 Nov 2017 - 07:46 PM,16.66,120.61,1,2.0,011 km N 36° W,Atok (Benguet)
7,30 Nov 2017 - 06:54 PM,18.09,120.70,36,1.9,002 km S 04° E,Dingras (Ilocos Norte)
8,30 Nov 2017 - 05:58 PM,10.09,123.27,8,2.8,004 km S 08° W,Guihulngan (Negros Oriental)
9,30 Nov 2017 - 01:59 PM,18.56,120.96,12,4.3,018 km S 85° E,Pagudpud (Ilocos Norte)
10,30 Nov 2017 - 09:16 AM,7.28,126.94,27,5.1,041 km S 83° E,Caraga (Davao Oriental)
11,30 Nov 2017 - 05:20 AM,12.48,125.74,4,2.6,042 km N 37° E,San Policarpo (Eastern Samar)
12,30 Nov 2017 - 12:39 AM,9.22,123.14,1,2.6,014 km N 78° W,Dauin (Negros Oriental)
13,29 Nov 2017 - 11:46 PM,14.00,120.41,86,2.1,025 km S 69° W,Nasugbu (Batangas)
14,29 Nov 2017 - 10:48 PM,13.10,124.51,14,2.8,035 km N 82° E,Prieto Diaz (Sorsogon)
15,29 Nov 2017 - 09:12 PM,12.99,124.53,6,3.9,037 km S 79° E,Prieto Diaz (Sorsogon)
16,29 Nov 2017 - 07:06 PM,13.30,123.69,9,2.2,006 km S 64° W,Malilipot (Albay)
17,29 Nov 2017 - 03:35 PM,9.77,123.93,33,2.0,004 km S 66° E,Antequera (Bohol)
18,29 Nov 2017 - 01:48 PM,5.89,124.50,1,2.5,017 km S 51° W,Kiamba (Sarangani)
19,29 Nov 2017 - 01:27 PM,7.11,123.42,1,2.6,038 km S 01° E,Tabina (Zamboanga del Sur)

In [168]:

df.to_csv("phivolcs_earthquakes_2017_11_November.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())

Data Saved: 382 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 Nov 2017 - 11:15 PM,10.10,123.38,4,2.3,002 km S 16° E,Guihulngan (Negros Oriental)
1,30 Nov 2017 - 09:50 PM,9.40,122.54,20,2.4,011 km S 85° W,Basay (Negros Oriental)
2,30 Nov 2017 - 09:38 PM,14.95,123.97,21,2.3,102 km N 12° W,Pandan (Catanduanes)
3,30 Nov 2017 - 09:15 PM,3.61,125.67,185,3.3,203 km S 06° E,Sarangani (Davao Occidental)
4,30 Nov 2017 - 08:54 PM,18.31,120.46,30,2.3,017 km S 81° W,Pasuquin (Ilocos Norte)

#December2017 (added condition)

In [169]:
import re
import pandas as pd

x  = "/content/2017dec.txt"
y = "phivolcs_earthquakes_2017_12_December.csv"

#added patterns
dt_rx   = re.compile(r"^\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM)$", re.I)
lat_rx  = re.compile(r"^\d{1,2}\.\d{2}$")
lon_rx  = re.compile(r"^\d{1,3}\.\d{2}$")
dep_rx  = re.compile(r"^\d+$")
mag_rx  = re.compile(r"^\d+(?:\.\d)?$")
month_rx = re.compile(r"^(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$", re.I)

#added
row_rx = re.compile(
    r"^(?P<datetime>\d{1,2}\s+\w+\s+\d{4}\s*-\s*\d{1,2}:\d{2}\s*(?:AM|PM))\s+"
    r"(?P<lat>\d{1,2}\.\d{2})\s+"
    r"(?P<long>\d{1,3}\.\d{2})\s+"
    r"(?P<depth>\d+)\s+"
    r"(?P<mag>\d+\.\d)$"
)

records = []
state = 0
cur = {}

def header_line(s: str) -> bool:
    hdrs = {
        "date - time (philippine time)",
        "latitude (ºn)", "latitude (°n)", "latitude (n)",
        "longitude (ºe)", "longitude (°e)", "longitude (e)",
        "depth (km)", "mag", "location", "seismicity maps", "description:"
    }
    t = s.strip().lower()
    return (t in hdrs) or bool(month_rx.match(s))

with open(x, encoding="utf-8", errors="ignore") as f:
    for raw in f:
        line = raw.strip()
        if not line or header_line(line):
            continue

        m = row_rx.match(line)
        if m:
            cur = {
                "Date - Time (Philippine Time)": m.group("datetime"),
                "Latitude (ºN)": m.group("lat"),
                "Longitude (ºE)": m.group("long"),
                "Depth (km)": m.group("depth"),
                "Mag": m.group("mag"),
            }
            state = 5
            continue


        if state == 0:  # datetime
            if dt_rx.match(line):
                cur = {"Date - Time (Philippine Time)": line}
                state = 1
            continue

        if state == 1:  # latitude
            if lat_rx.match(line):
                cur["Latitude (ºN)"] = line
                state = 2
            else:
                if dt_rx.match(line):
                    cur = {"Date - Time (Philippine Time)": line}
                    state = 1
            continue

        if state == 2:  # longitude
            if lon_rx.match(line):
                cur["Longitude (ºE)"] = line
                state = 3
            else:
                state = 0
            continue

        if state == 3:  # depth
            if dep_rx.match(line):
                cur["Depth (km)"] = line
                state = 4
            else:
                state = 0
            continue

        if state == 4:  # magnitude
            if mag_rx.match(line):
                cur["Mag"] = line
                state = 5
            else:
                state = 0
            continue

        if state == 5:  # location
            cur["Location"] = line if line else None
            records.append(cur)
            state = 0
            cur = {}

df = pd.DataFrame.from_records(records, columns=[
    "Date - Time (Philippine Time)",
    "Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag", "Location"
])

for col in ["Latitude (ºN)", "Longitude (ºE)", "Depth (km)", "Mag"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")


df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
df["Coordinates"] = df["Coordinates"].str.strip()

cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)","Depth (km)", "Mag", "Coordinates", "Location"]
df = df[cols]

dups_mask = df.duplicated(subset=["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)"], keep=False)
duplicates = df[dups_mask]
print("Duplicates found:\n", duplicates if not duplicates.empty else "None")
print("Dups No:", int(dups_mask.sum()))
print("Nulls per column:\n", df.isnull().sum())


df.to_csv(y, index=False, encoding="utf-8-sig")
print(f"Data Saved: {len(df)} rows → {y}")

Duplicates found:
 None
Dups No: 0
Nulls per column:
 Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64
Data Saved: 225 rows → phivolcs_earthquakes_2017_12_December.csv

In [170]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []

In [171]:
'''
fix = {
    216: {"Coordinates": "004 km S 71° E", "Location": "Santa Teresita (Batangas)"},
    217: {"Coordinates": "036 km S 74° W", "Location": "Calayan (Cagayan)"},
    218: {"Coordinates": "021 km N 55° E", "Location": "Buhi (Camarines Sur)"},
    219: {"Coordinates": "033 km S 34° E", "Location": "Palanan (Isabela)"},

}


for idx, changes in fix.items():
    for col, val in changes.items():
        df.at[idx, col] = val

'''

'\nfix = {\n    216: {"Coordinates": "004 km S 71° E", "Location": "Santa Teresita (Batangas)"},\n    217: {"Coordinates": "036 km S 74° W", "Location": "Calayan (Cagayan)"},\n    218: {"Coordinates": "021 km N 55° E", "Location": "Buhi (Camarines Sur)"},\n    219: {"Coordinates": "033 km S 34° E", "Location": "Palanan (Isabela)"},\n\n}\n\n\nfor idx, changes in fix.items():\n    for col, val in changes.items():\n        df.at[idx, col] = val\n\n'

In [172]:
df.head(20)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,24 Dec 2017 - 11:10 AM,13.86,120.55,147,2.8,010 km N 71° W,Calatagan (Batangas)
1,24 Dec 2017 - 12:01 AM,12.42,123.74,1,2.1,006 km S 23° W,San Fernando (Masbate)
2,23 Dec 2017 - 11:31 PM,16.01,121.58,33,2.2,023 km S 05° W,Nagtipunan (Quirino)
3,23 Dec 2017 - 07:25 PM,9.33,126.35,14,3.5,018 km N 71° E,Cortes (Surigao Del Sur)
4,23 Dec 2017 - 06:49 PM,8.79,126.33,28,2.5,004 km S 65° E,Marihatag (Surigao Del Sur)
5,23 Dec 2017 - 04:53 PM,13.33,120.38,2,2.2,014 km S 47° W,Paluan (Occidental Mindoro)
6,23 Dec 2017 - 02:31 PM,7.19,127.47,22,3.3,008 km S 72° W,Manay (Davao Oriental)
7,23 Dec 2017 - 01:55 PM,17.33,120.28,26,2.4,017 km N 89° W,San Esteban (Ilocos Sur)
8,23 Dec 2017 - 06:32 AM,18.29,121.02,12,2.0,022 km S 30° E,Adams (Ilocos Norte)
9,23 Dec 2017 - 04:04 AM,7.63,126.66,25,3.0,025 km N 63° E,Baganga (Davao Oriental)
10,22 Dec 2017 - 10:52 PM,17.89,121.57,58,2.7,009 km S 76° W,Alcala (Cagayan)
11,22 Dec 2017 - 07:16 PM,15.33,121.92,10,2.5,046 km N 17° E,Panukulan (Quezon)
12,22 Dec 2017 - 06:52 PM,14.99,119.79,1,2.4,031 km S 75° W,San Felipe (Zambales)
13,22 Dec 2017 - 04:56 PM,16.20,119.41,20,2.8,043 km N 77° W,Agno (Pangasinan)
14,22 Dec 2017 - 01:33 PM,3.24,126.58,15,4.3,272 km S 27° E,Sarangani (Davao Occidental)
15,22 Dec 2017 - 11:14 AM,9.37,125.67,26,2.1,014 km S 45° E,Kitcharao (Agusan del Norte)
16,22 Dec 2017 - 08:47 AM,5.65,125.90,17,3.8,040 km S 51° E,Jose Abad Santos (Davao Occidental)
17,22 Dec 2017 - 07:48 AM,13.16,124.36,20,2.1,021 km N 58° E,Prieto Diaz (Sorsogon)
18,22 Dec 2017 - 07:07 AM,13.58,120.74,111,2.8,015 km N 04° E,Abra de Ilog (Occidental Mindoro)
19,22 Dec 2017 - 05:21 AM,10.75,124.90,1,2.4,012 km N 88° W,Abuyog (Leyte)

In [173]:
'''
df.to_csv("phivolcs_earthquakes_2017_11_November.csv", index=False, encoding="utf-8")
print(f"Data Saved: {len(df)} rows")
display(df.head())
'''

'\ndf.to_csv("phivolcs_earthquakes_2017_11_November.csv", index=False, encoding="utf-8")\nprint(f"Data Saved: {len(df)} rows")\ndisplay(df.head())\n'