#DOCUMENTATION

Paki basa tung july 2025 nako kay naay problema didto so gi lahi ang code..

#IMPORTED

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

#Fetching (nah wala to)

In [ ]:
'''
url = "https://earthquake.phivolcs.dost.gov.ph"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")
'''

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

#Year 2025

##Extraction (October 2025)

In [ ]:
#fetching on that specific link (For october)
#iba naman sa september and onwards ha

url = "https://earthquake.phivolcs.dost.gov.ph"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()
#-------ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
        "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]
#-------ocd lang to
    df.to_csv("phivolcs_earthquakes(October_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 963 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,03 October 2025 - 09:07 PM,11.09,124.13,005,2.4,015km N 88Â° E,City Of Bogo (Cebu)
1,03 October 2025 - 09:00 PM,10.96,123.89,011,1.9,014km S 46Â° W,City Of Bogo (Cebu)
2,03 October 2025 - 08:57 PM,11.16,123.99,007,2.3,013km N 05Â° E,City Of Bogo (Cebu)
3,03 October 2025 - 08:53 PM,11.10,124.09,005,1.7,014km N 63Â° E,City Of Bogo (Cebu)
4,03 October 2025 - 08:42 PM,11.00,123.93,003,2.5,008km S 44Â° W,City Of Bogo (Cebu)

In [ ]:
#just for checking so i will docs string this
'''
with open("page.html", "w", encoding="utf-8") as f:
    f.write(soup.prettify())
'''

'\nwith open("page.html", "w", encoding="utf-8") as f:\n    f.write(soup.prettify())\n'

In [ ]:
df.head(10)

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,03 October 2025 - 09:07 PM,11.09,124.13,005,2.4,015km N 88Â° E,City Of Bogo (Cebu)
1,03 October 2025 - 09:00 PM,10.96,123.89,011,1.9,014km S 46Â° W,City Of Bogo (Cebu)
2,03 October 2025 - 08:57 PM,11.16,123.99,007,2.3,013km N 05Â° E,City Of Bogo (Cebu)
3,03 October 2025 - 08:53 PM,11.10,124.09,005,1.7,014km N 63Â° E,City Of Bogo (Cebu)
4,03 October 2025 - 08:42 PM,11.00,123.93,003,2.5,008km S 44Â° W,City Of Bogo (Cebu)
5,03 October 2025 - 08:37 PM,11.28,124.14,011,2.4,032km N 34Â° E,City Of Bogo (Cebu)
6,03 October 2025 - 08:28 PM,10.96,123.94,002,3.4,010km S 27Â° W,City Of Bogo (Cebu)
7,03 October 2025 - 08:19 PM,11.15,123.92,006,3.2,013km N 29Â° W,City Of Bogo (Cebu)
8,03 October 2025 - 08:17 PM,11.13,123.95,010,2.8,010km N 17Â° W,City Of Bogo (Cebu)
9,03 October 2025 - 08:15 PM,10.97,123.98,016,2.3,008km S 02Â° E,City Of Bogo (Cebu)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
835    01 October 2025 - 05:46 AM         11.19         123.95        022
836    01 October 2025 - 05:46 AM         11.19         123.95        022
920    01 October 2025 - 01:52 AM         11.16         123.98        031
921    01 October 2025 - 01:52 AM         11.16         123.98        031

     Mag     Coordinates             Location
835  1.8  016km N 10Â° W  City Of Bogo (Cebu)
836  1.8  016km N 10Â° W  City Of Bogo (Cebu)
920  2.6  013km N 01Â° W  City Of Bogo (Cebu)
921  2.6  013km N 01Â° W  City Of Bogo (Cebu)


Dups No: 2


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Extraction (Sepctember 2025)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_September.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()
#-------ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
        "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]
#-------ocd lang to
    df.to_csv("phivolcs_earthquakes(September_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1509 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 September 2025 - 11:59 PM,11.08,124.06,007,3.8,010km N 67Â° E,City Of Bogo (Cebu)
1,30 September 2025 - 11:51 PM,10.77,123.70,011,2.6,015km N 70Â° W,Tuburan (Cebu)
2,30 September 2025 - 11:49 PM,11.18,123.99,030,2.0,015km N 03Â° E,City Of Bogo (Cebu)
3,30 September 2025 - 11:47 PM,11.15,124.16,006,2.6,023km N 60Â° E,City Of Bogo (Cebu)
4,30 September 2025 - 11:42 PM,11.12,124.03,031,2.2,010km N 31Â° E,City Of Bogo (Cebu)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
853  13 September 2025 - 06:57 AM         09.24         126.90        015
854  13 September 2025 - 06:57 AM         09.24         126.90        015

     Mag     Coordinates                   Location
853  2.3  074km N 66Â° E  Bayabas (Surigao Del Sur)
854  2.3  074km N 66Â° E  Bayabas (Surigao Del Sur)


Dups No: 1


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

##Extraction (August 2025)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_August.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:
    df = pd.DataFrame(all_rows, columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip()
#-------ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
        "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]
#-------ocd lang to
    df.to_csv("phivolcs_earthquakes(August_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1632 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 August 2025 - 11:56 PM,13.35,120.66,008,1.9,012km S 35Â° W,Abra De Ilog (Occidental Mindoro)
1,31 August 2025 - 11:38 PM,08.84,126.34,019,1.5,006km N 46Â° E,Marihatag (Surigao Del Sur)
2,31 August 2025 - 11:23 PM,13.61,120.56,035,1.4,024km N 26Â° E,Paluan (Occidental Mindoro)
3,31 August 2025 - 11:19 PM,06.51,126.55,004,1.9,056km S 74Â° E,Governor Generoso (Davao Oriental)
4,31 August 2025 - 10:31 PM,18.67,120.89,011,1.9,016km N 41Â° E,Pagudpud (Ilocos Norte)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

##Extraction (July 2025)
THERE WAS A CHANGE IN THE CODE. IT MISSES SOME COLUMNS SO BETTER USE THIS FOR THE FOLLOWING MONTHS

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_July.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip() + " of"

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    df.to_csv("phivolcs_earthquakes(July_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1421 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 July 2025 - 11:50 PM,08.06,126.25,033,1.6,018km N 84Â° W of,Lingig (Surigao Del Sur)
1,31 July 2025 - 11:50 PM,08.63,126.36,022,1.4,020km S 49Â° E of,San Agustin (Surigao Del Sur)
2,31 July 2025 - 11:46 PM,09.78,123.02,026,2.0,011km N 65Â° E of,Mabinay (Negros Oriental)
3,31 July 2025 - 11:45 PM,08.32,126.55,045,1.6,024km S 78Â° E of,Hinatuan (Surigao Del Sur)
4,31 July 2025 - 11:27 PM,13.40,120.17,007,2.7,032km S 86Â° W of,Paluan (Occidental Mindoro)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Extraction (June 2025)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_June.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip() + " of"

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    df.to_csv("phivolcs_earthquakes(June_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1637 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 June 2025 - 11:25 PM,20.52,121.89,074,2.1,020km N 06Â° E of,Sabtang (Batanes)
1,30 June 2025 - 10:47 PM,10.26,125.85,029,1.6,034km N 37Â° W of,Santa Monica (Surigao Del Norte)
2,30 June 2025 - 10:19 PM,09.05,126.41,024,2.3,016km N 58Â° E of,Bayabas (Surigao Del Sur)
3,30 June 2025 - 09:48 PM,17.39,120.27,012,2.1,021km S 34Â° W of,Caoayan (Ilocos Sur)
4,30 June 2025 - 09:40 PM,08.54,127.14,017,2.2,091km N 78Â° E of,Hinatuan (Surigao Del Sur)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Extraction (May 2025)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_May.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip() + " of"

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    df.to_csv("phivolcs_earthquakes(May_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1559 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 May 2025 - 11:37 PM,15.46,121.95,009,2.2,053km S 52Â° E of,Baler (Aurora)
1,31 May 2025 - 11:12 PM,08.07,127.30,014,2.5,098km N 56Â° E of,Baganga (Davao Oriental)
2,31 May 2025 - 10:57 PM,16.43,122.23,018,2.0,005km N 26Â° E of,Dilasag (Aurora)
3,31 May 2025 - 10:20 PM,09.73,127.51,029,3.0,149km S 88Â° E of,General Luna (Surigao Del Norte)
4,31 May 2025 - 07:46 PM,16.96,122.38,009,2.2,012km S 24Â° W of,Palanan (Isabela)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Extraction (April 2025)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_April.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip() + " of"

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    df.to_csv("phivolcs_earthquakes(April_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1332 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,30 April 2025 - 11:53 PM,04.47,126.36,019,4.4,147km S 45Â° E of,Balut Island (Municipality Of Sarangani) (Dava...
1,30 April 2025 - 11:48 PM,09.94,126.07,033,2.0,006km S 31Â° E of,San Benito (Surigao Del Norte)
2,30 April 2025 - 10:44 PM,07.43,127.24,023,3.0,076km N 82Â° E of,Caraga (Davao Oriental)
3,30 April 2025 - 08:49 PM,09.43,122.18,024,2.6,037km S 59Â° W of,Hinoba-an (Negros Occidental)
4,30 April 2025 - 08:10 PM,08.97,126.11,071,2.5,009km N 74Â° E of,San Miguel (Surigao Del Sur)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Extraction (March 2025)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_March.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip() + " of"

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    df.to_csv("phivolcs_earthquakes(March_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1401 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 March 2025 - 11:32 PM,06.78,125.67,016,2.2,028km S 78Â° E of,Santa Cruz (Davao Del Sur)
1,31 March 2025 - 11:07 PM,09.75,122.28,026,2.1,017km S 81Â° W of,City Of Sipalay (Negros Occidental)
2,31 March 2025 - 10:35 PM,09.70,122.28,025,1.9,019km S 64Â° W of,City Of Sipalay (Negros Occidental)
3,31 March 2025 - 10:17 PM,13.73,120.74,075,2.2,017km S 46Â° E of,Calatagan (Batangas)
4,31 March 2025 - 09:38 PM,08.60,127.11,030,1.8,089km N 73Â° E of,Hinatuan (Surigao Del Sur)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Extraction (February 2025)
Removed an Index here. Unnatural Duplicate.

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_February.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip() + " of"

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    df.to_csv("phivolcs_earthquakes(February_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1213 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,28 February 2025 - 11:15 PM,11.30,125.90,010,2.4,031km S 80Â° E of,Hernani (Eastern Samar)
1,28 February 2025 - 09:56 PM,06.68,126.62,023,2.4,045km S 24Â° E of,Tarragona (Davao Oriental)
2,28 February 2025 - 09:39 PM,10.17,126.64,001,1.4,064km N 75Â° E of,Burgos (Surigao Del Norte)
3,28 February 2025 - 09:38 PM,07.67,126.04,008,2.1,005km S 88Â° W of,Compostela (Davao De Oro)
4,28 February 2025 - 09:33 PM,06.04,122.60,034,2.4,071km S 45Â° E of,Al-barka (Basilan)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

'''
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
514   16 February 2025 - 07:47 AM         10.41         123.22        005
601   16 February 2025 - 07:47 AM         10.41         123.22        005

     Mag        Coordinates                           Location
514  2.5  002km N 10Â° E of  City Of Canlaon (Negros Oriental)
601  2.5  002km N 10Â° E of  City Of Canlaon (Negros Oriental)


Dups No: 1

Nasaag si feb 16 sa 15 so remove ito

'''

    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
514   16 February 2025 - 07:47 AM         10.41         123.22        005
601   16 February 2025 - 07:47 AM         10.41         123.22        005

     Mag        Coordinates                           Location
514  2.5  002km N 10Â° E of  City Of Canlaon (Negros Oriental)
601  2.5  002km N 10Â° E of  City Of Canlaon (Negros Oriental)


Dups No: 1


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df = df.drop(index=601)

In [ ]:
    df.to_csv("phivolcs_earthquakes(February_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())

Data Saved: 1212 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,28 February 2025 - 11:15 PM,11.30,125.90,010,2.4,031km S 80Â° E of,Hernani (Eastern Samar)
1,28 February 2025 - 09:56 PM,06.68,126.62,023,2.4,045km S 24Â° E of,Tarragona (Davao Oriental)
2,28 February 2025 - 09:39 PM,10.17,126.64,001,1.4,064km N 75Â° E of,Burgos (Surigao Del Norte)
3,28 February 2025 - 09:38 PM,07.67,126.04,008,2.1,005km S 88Â° W of,Compostela (Davao De Oro)
4,28 February 2025 - 09:33 PM,06.04,122.60,034,2.4,071km S 45Â° E of,Al-barka (Basilan)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

##Extraction (January 2025)

In [ ]:
url = "https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2025/2025_January.html"
response = requests.get(url, verify=False) #skipping verification gang

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.prettify()[:500])
    print("Success!")
else:
    print("Failed fetcher")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0040)https://earthquake.phivolcs.dost.gov.ph/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="150" http-equiv="refresh"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Seismological Observation and Earthquake Prediction Division
  </title>
  <style type="text/css">
   span.auto-style12
  {font
Success!

In [ ]:
all_rows = []
headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

tables = soup.find_all("table", {"class": "MsoNormalTable"})

for table in tables:
    ths = [th.get_text(strip=True) for th in table.find_all("th")]
    if ths and "Date - Time" in ths[0]:
        for tr in table.find_all("tr")[1:]:
            cols = [td.get_text(strip=True) for td in tr.find_all("td")]
            if cols:
                all_rows.append(cols)

if all_rows:

    df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

    #split sesame
    df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
    df["Coordinates"] = df["Coordinates"].str.strip() + " of"

#-----ocd lang to
    cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
            "Depth (km)", "Mag", "Coordinates", "Location"]
    df = df[cols]


    df.to_csv("phivolcs_earthquakes(January_2025).csv", index=False, encoding="utf-8")
    print(f"Data Saved: {len(df)} rows")
    display(df.head())
else:
    print("No Data")

Data Saved: 1441 rows

,Date - Time (Philippine Time),Latitude (ºN),Longitude (ºE),Depth (km),Mag,Coordinates,Location
0,31 January 2025 - 11:51 PM,12.48,123.68,005,2.5,009km S 89Â° W of,San Fernando (Masbate)
1,31 January 2025 - 11:12 PM,15.68,119.79,034,1.6,015km S 55Â° W of,Santa Cruz (Zambales)
2,31 January 2025 - 11:01 PM,18.99,120.71,001,2.5,053km S 76Â° W of,Dalupiri Island (Calayan) (Cagayan)
3,31 January 2025 - 09:59 PM,12.92,121.12,040,1.5,033km S 32Â° W of,Victoria (Oriental Mindoro)
4,31 January 2025 - 09:22 PM,08.36,126.25,113,2.4,010km S 85Â° W of,Hinatuan (Surigao Del Sur)

In [ ]:
cnt = df.duplicated().sum()

duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("\n")
print("Dups No:", cnt)
print("\n")
print("This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.")

Empty DataFrame
Columns: [Date - Time (Philippine Time), Latitude (ºN), Longitude (ºE), Depth (km), Mag, Coordinates, Location]
Index: []


Dups No: 0


This is an earthquake data so duplicates are okay. Just make sure to double check the website and confirm.

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

In [ ]:
df.isnull().sum()

Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

#Year 2024

In [2]:
pages = {
    "2024/2024_January": "January_2024",
    "2024/2024_February": "February_2024",
    "2024/2024_March": "March_2024",
    "2024/2024_April": "April_2024",
    "2024/2024_May": "May_2024",
    "2024/2024_June": "June_2024",
    "2024/2024_July": "July_2024",
    "2024/2024_August": "August_2024",
    "2024/2024_September": "September_2024",
    "2024/2024_October": "October_2024",
    "2024/2024_November": "November_2024",
    "2024/2024_December": "December_2024",
}

headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

for path, filename in pages.items():
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{path}.html"
    print(f"\nFetching: {url}")
    response = requests.get(url, verify=False)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        print("Success!")
    else:
        print("Failed fetcher")
        continue

    all_rows = []
    tables = soup.find_all("table", {"class": "MsoNormalTable"})

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                cols = [td.get_text(strip=True) for td in tr.find_all("td")]
                if cols:
                    all_rows.append(cols)

    if all_rows:
        df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

        df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
        df["Coordinates"] = df["Coordinates"].str.strip() + " of"

        cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
                "Depth (km)", "Mag", "Coordinates", "Location"]
        df = df[cols]

        out_file = f"phivolcs_earthquakes({filename}).csv"
        df.to_csv(out_file, index=False, encoding="utf-8")
        print(f"Data Saved: {len(df)} rows to {out_file}")

        cnt = df.duplicated().sum()
        duplicates = df[df.duplicated(keep=False)]
        print("Duplicate rows:", cnt)
        if cnt > 0:
            print(duplicates.head())

        print("\nNull counts:")
        print(df.isnull().sum())

    else:
        print("No Data")

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_January.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1897 rows to phivolcs_earthquakes(January_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_February.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1457 rows to phivolcs_earthquakes(February_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_March.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1634 rows to phivolcs_earthquakes(March_2024).csv
Duplicate rows: 1
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
1345      06 March 2024 - 11:12 AM         08.38         126.76        006
1397      06 March 2024 - 11:12 AM         08.38         126.76        006

      Mag        Coordinates                    Location
1345  1.9  047km N 88Â° E of  Hinatuan (Surigao Del Sur)
1397  1.9  047km N 88Â° E of  Hinatuan (Surigao Del Sur)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_April.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1463 rows to phivolcs_earthquakes(April_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_May.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1509 rows to phivolcs_earthquakes(May_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_June.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1540 rows to phivolcs_earthquakes(June_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_July.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1476 rows to phivolcs_earthquakes(July_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_August.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 2057 rows to phivolcs_earthquakes(August_2024).csv
Duplicate rows: 3
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
904      15 August 2024 - 12:04 AM         06.68         126.45        034
906      15 August 2024 - 12:04 AM         06.68         126.45        034
1267     08 August 2024 - 07:20 PM         08.08         126.79        017
1268     08 August 2024 - 07:20 PM         08.08         126.79        017
1766     03 August 2024 - 08:54 PM         08.11         126.96        010

      Mag        Coordinates                       Location
904   2.7  040km S 41Â° E of  City Of Mati (Davao Oriental)
906   2.7  040km S 41Â° E of  City Of Mati (Davao Oriental)
1267  2.2  042km N 83Â° E of       Lingig (Surigao Del Sur)
1268  2.2  042km N 83Â° E of       Lingig (Surigao Del Sur)
1766  2.8  060km N 83Â° E of       Lingig (Surigao Del Sur)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_September.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1441 rows to phivolcs_earthquakes(September_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_October.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1247 rows to phivolcs_earthquakes(October_2024).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_November.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1198 rows to phivolcs_earthquakes(November_2024).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
244   23 November 2024 - 07:58 PM         17.85         120.67        005
322   23 November 2024 - 07:58 PM         17.85         120.67        005

     Mag        Coordinates                  Location
244  2.2  007km S 02Â° E of  Nueva Era (Ilocos Norte)
322  2.2  007km S 02Â° E of  Nueva Era (Ilocos Norte)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2024/2024_December.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1229 rows to phivolcs_earthquakes(December_2024).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
212   27 December 2024 - 01:00 AM         06.75         125.09        021
213   27 December 2024 - 01:00 AM         06.75         125.09        021

     Mag        Coordinates                   Location
212  2.2  007km N 89Â° W of  Magsaysay (Davao Del Sur)
213  2.2  007km N 89Â° W of  Magsaysay (Davao Del Sur)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

# Year 2023

In [3]:
pages = {
    "2023/2023_January": "January_2023",
    "2023/2023_February": "February_2023",
    "2023/2023_March": "March_2023",
    "2023/2023_April": "April_2023",
    "2023/2023_May": "May_2023",
    "2023/2023_June": "June_2023",
    "2023/2023_July": "July_2023",
    "2023/2023_August": "August_2023",
    "2023/2023_September": "September_2023",
    "2023/2023_October": "October_2023",
    "2023/2023_November": "November_2023",
    "2023/2023_December": "December_2023",
}

headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

for path, filename in pages.items():
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{path}.html"
    print(f"\nFetching: {url}")
    response = requests.get(url, verify=False)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        print("Success!")
    else:
        print("Failed fetcher")
        continue

    all_rows = []
    tables = soup.find_all("table", {"class": "MsoNormalTable"})

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                cols = [td.get_text(strip=True) for td in tr.find_all("td")]
                if cols:
                    all_rows.append(cols)

    if all_rows:
        df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

        df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
        df["Coordinates"] = df["Coordinates"].str.strip() + " of"

        cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
                "Depth (km)", "Mag", "Coordinates", "Location"]
        df = df[cols]

        out_file = f"phivolcs_earthquakes({filename}).csv"
        df.to_csv(out_file, index=False, encoding="utf-8")
        print(f"Data Saved: {len(df)} rows to {out_file}")

        cnt = df.duplicated().sum()
        duplicates = df[df.duplicated(keep=False)]
        print("Duplicate rows:", cnt)
        if cnt > 0:
            print(duplicates.head())

        print("\nNull counts:")
        print(df.isnull().sum())

    else:
        print("No Data")

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_January.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 907 rows to phivolcs_earthquakes(January_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_February.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1091 rows to phivolcs_earthquakes(February_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_March.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1249 rows to phivolcs_earthquakes(March_2023).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
741      11 March 2023 - 01:14 AM         16.29         122.39        008
757      11 March 2023 - 01:14 AM         16.29         122.39        008

     Mag        Coordinates          Location
741  2.7  023km S 58Â° E of  Dilasag (Aurora)
757  2.7  023km S 58Â° E of  Dilasag (Aurora)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         2
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_April.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1242 rows to phivolcs_earthquakes(April_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_May.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1114 rows to phivolcs_earthquakes(May_2023).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
331        12 May 2023 - 05:29 AM         07.92         124.10        004
696        12 May 2023 - 05:29 AM         07.92         124.10        004

     Mag        Coordinates                 Location
331  2.9  008km N 14Â° W of  Madalum (Lanao Del Sur)
696  2.9  008km N 14Â° W of  Madalum (Lanao Del Sur)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_June.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1075 rows to phivolcs_earthquakes(June_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_July.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1085 rows to phivolcs_earthquakes(July_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_August.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1138 rows to phivolcs_earthquakes(August_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_September.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1102 rows to phivolcs_earthquakes(September_2023).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
783  09 September 2023 - 04:58 PM         17.96         120.70        001
853  09 September 2023 - 04:58 PM         17.96         120.70        001

     Mag        Coordinates              Location
783  3.3  005km S 64Â° E of  Banna (Ilocos Norte)
853  3.3  005km S 64Â° E of  Banna (Ilocos Norte)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_October.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1179 rows to phivolcs_earthquakes(October_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_November.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1164 rows to phivolcs_earthquakes(November_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2023/2023_December.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 4285 rows to phivolcs_earthquakes(December_2023).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

# Year 2022

In [4]:
pages = {
    "2022/2022_January": "January_2022",
    "2022/2022_February": "February_2022",
    "2022/2022_March": "March_2022",
    "2022/2022_April": "April_2022",
    "2022/2022_May": "May_2022",
    "2022/2022_June": "June_2022",
    "2022/2022_July": "July_2022",
    "2022/2022_August": "August_2022",
    "2022/2022_September": "September_2022",
    "2022/2022_October": "October_2022",
    "2022/2022_November": "November_2022",
    "2022/2022_December": "December_2022",
}

headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

for path, filename in pages.items():
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{path}.html"
    print(f"\nFetching: {url}")
    response = requests.get(url, verify=False)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        print("Success!")
    else:
        print("Failed fetcher")
        continue

    all_rows = []
    tables = soup.find_all("table", {"class": "MsoNormalTable"})

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                cols = [td.get_text(strip=True) for td in tr.find_all("td")]
                if cols:
                    all_rows.append(cols)

    if all_rows:
        df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

        df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
        df["Coordinates"] = df["Coordinates"].str.strip() + " of"

        cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
                "Depth (km)", "Mag", "Coordinates", "Location"]
        df = df[cols]

        out_file = f"phivolcs_earthquakes({filename}).csv"
        df.to_csv(out_file, index=False, encoding="utf-8")
        print(f"Data Saved: {len(df)} rows to {out_file}")

        cnt = df.duplicated().sum()
        duplicates = df[df.duplicated(keep=False)]
        print("Duplicate rows:", cnt)
        if cnt > 0:
            print(duplicates.head())

        print("\nNull counts:")
        print(df.isnull().sum())

    else:
        print("No Data")

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_January.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 787 rows to phivolcs_earthquakes(January_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_February.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 638 rows to phivolcs_earthquakes(February_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_March.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1432 rows to phivolcs_earthquakes(March_2022).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
740      17 March 2022 - 03:34 AM         14.04         119.45        009
741      17 March 2022 - 03:34 AM         14.04         119.45        009

     Mag        Coordinates                     Location
740  2.6  075km N 74Â° W of  Lubang (Occidental Mindoro)
741  2.6  075km N 74Â° W of  Lubang (Occidental Mindoro)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_April.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1153 rows to phivolcs_earthquakes(April_2022).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
519      16 April 2022 - 10:10 PM         07.07         123.67        028
520      16 April 2022 - 10:10 PM         07.07         123.67        028

     Mag        Coordinates                    Location
519  1.9  052km S 33Â° E of  Tabina (Zamboanga Del Sur)
520  1.9  052km S 33Â° E of  Tabina (Zamboanga Del Sur)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_May.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1051 rows to phivolcs_earthquakes(May_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_June.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1043 rows to phivolcs_earthquakes(June_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_July.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1799 rows to phivolcs_earthquakes(July_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_August.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1913 rows to phivolcs_earthquakes(August_2022).csv
Duplicate rows: 1
     Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
476      23 August 2022 - 06:57 AM         18.18         122.17        014
1673     23 August 2022 - 06:57 AM         18.18         122.17        014

      Mag        Coordinates           Location
476   2.2  020km S 62Â° E of  Gonzaga (Cagayan)
1673  2.2  020km S 62Â° E of  Gonzaga (Cagayan)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_September.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1118 rows to phivolcs_earthquakes(September_2022).csv
Duplicate rows: 1
    Date - Time (Philippine Time) Latitude (ºN) Longitude (ºE) Depth (km)  \
627  13 September 2022 - 12:50 AM         13.77         120.67        098
689  13 September 2022 - 12:50 AM         13.77         120.67        098

     Mag        Coordinates              Location
627  1.8  008km S 32Â° E of  Calatagan (Batangas)
689  1.8  008km S 32Â° E of  Calatagan (Batangas)

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_October.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1354 rows to phivolcs_earthquakes(October_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_November.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 1177 rows to phivolcs_earthquakes(November_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

Fetching: https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/2022/2022_December.html

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'earthquake.phivolcs.dost.gov.ph'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Success!
Data Saved: 872 rows to phivolcs_earthquakes(December_2022).csv
Duplicate rows: 0

Null counts:
Date - Time (Philippine Time)    0
Latitude (ºN)                    0
Longitude (ºE)                   0
Depth (km)                       0
Mag                              0
Coordinates                      0
Location                         0
dtype: int64

# Year 2021

In [ ]:
pages = {
  "2021/2021_January": "January_2021",
  "2021/2021_February": "February_2021",
  "2021/2021_March": "March_2021",
  "2021/2021_April": "April_2021",
  "2021/2021_May": "May_2021",
  "2021/2021_June": "June_2021",
  "2021/2021_July": "July_2021",
  "2021/2021_August": "August_2021",
  "2021/2021_September": "September_2021",
  "2021/2021_October": "October_2021",
  "2021/2021_November": "November_2021",
  "2021/2021_December": "December_2021"
}

headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

for path, filename in pages.items():
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{path}.html"
    print(f"\nFetching: {url}")
    response = requests.get(url, verify=False)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        print("Success!")
    else:
        print("Failed fetcher")
        continue

    all_rows = []
    tables = soup.find_all("table", {"class": "MsoNormalTable"})

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                cols = [td.get_text(strip=True) for td in tr.find_all("td")]
                if cols:
                    all_rows.append(cols)

    if all_rows:
        df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

        df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
        df["Coordinates"] = df["Coordinates"].str.strip() + " of"

        cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
                "Depth (km)", "Mag", "Coordinates", "Location"]
        df = df[cols]

        out_file = f"phivolcs_earthquakes({filename}).csv"
        df.to_csv(out_file, index=False, encoding="utf-8")
        print(f"Data Saved: {len(df)} rows to {out_file}")

        cnt = df.duplicated().sum()
        duplicates = df[df.duplicated(keep=False)]
        print("Duplicate rows:", cnt)
        if cnt > 0:
            print(duplicates.head())

        print("\nNull counts:")
        print(df.isnull().sum())

    else:
        print("No Data")

# Year 2020

In [ ]:
pages = {
"2020/2020_January": "January_2020",
"2020/2020_February": "February_2020",
"2020/2020_March": "March_2020",
"2020/2020_April": "April_2020",
"2020/2020_May": "May_2020",
"2020/2020_June": "June_2020",
"2020/2020_July": "July_2020",
"2020/2020_August": "August_2020",
"2020/2020_September": "September_2020",
"2020/2020_October": "October_2020",
"2020/2020_November": "November_2020",
"2020/2020_December": "December_2020"
}

headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

for path, filename in pages.items():
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{path}.html"
    print(f"\nFetching: {url}")
    response = requests.get(url, verify=False)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        print("Success!")
    else:
        print("Failed fetcher")
        continue

    all_rows = []
    tables = soup.find_all("table", {"class": "MsoNormalTable"})

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                cols = [td.get_text(strip=True) for td in tr.find_all("td")]
                if cols:
                    all_rows.append(cols)

    if all_rows:
        df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

        df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
        df["Coordinates"] = df["Coordinates"].str.strip() + " of"

        cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
                "Depth (km)", "Mag", "Coordinates", "Location"]
        df = df[cols]

        out_file = f"phivolcs_earthquakes({filename}).csv"
        df.to_csv(out_file, index=False, encoding="utf-8")
        print(f"Data Saved: {len(df)} rows to {out_file}")

        cnt = df.duplicated().sum()
        duplicates = df[df.duplicated(keep=False)]
        print("Duplicate rows:", cnt)
        if cnt > 0:
            print(duplicates.head())

        print("\nNull counts:")
        print(df.isnull().sum())

    else:
        print("No Data")

# Year 2019

In [ ]:
pages = {
"2019/2019_January": "January_2019",
"2019/2019_February": "February_2019",
"2019/2019_March": "March_2019",
"2019/2019_April": "April_2019",
"2019/2019_May": "May_2019",
"2019/2019_June": "June_2019",
"2019/2019_July": "July_2019",
"2019/2019_August": "August_2019",
"2019/2019_September": "September_2019",
"2019/2019_October": "October_2019",
"2019/2019_November": "November_2019",
"2019/2019_December": "December_2019"
}

headers = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
           "Depth (km)", "Mag", "Location"]

for path, filename in pages.items():
    url = f"https://earthquake.phivolcs.dost.gov.ph/EQLatest-Monthly/{path}.html"
    print(f"\nFetching: {url}")
    response = requests.get(url, verify=False)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        print("Success!")
    else:
        print("Failed fetcher")
        continue

    all_rows = []
    tables = soup.find_all("table", {"class": "MsoNormalTable"})

    for table in tables:
        ths = [th.get_text(strip=True) for th in table.find_all("th")]
        if ths and "Date - Time" in ths[0]:
            for tr in table.find_all("tr")[1:]:
                cols = [td.get_text(strip=True) for td in tr.find_all("td")]
                if cols:
                    all_rows.append(cols)

    if all_rows:
        df = pd.DataFrame([row[:6] for row in all_rows], columns=headers)

        df[["Coordinates", "Location"]] = df["Location"].str.split("of ", n=1, expand=True)
        df["Coordinates"] = df["Coordinates"].str.strip() + " of"

        cols = ["Date - Time (Philippine Time)", "Latitude (ºN)", "Longitude (ºE)",
                "Depth (km)", "Mag", "Coordinates", "Location"]
        df = df[cols]

        out_file = f"phivolcs_earthquakes({filename}).csv"
        df.to_csv(out_file, index=False, encoding="utf-8")
        print(f"Data Saved: {len(df)} rows to {out_file}")

        cnt = df.duplicated().sum()
        duplicates = df[df.duplicated(keep=False)]
        print("Duplicate rows:", cnt)
        if cnt > 0:
            print(duplicates.head())

        print("\nNull counts:")
        print(df.isnull().sum())

    else:
        print("No Data")